// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright contributors to the Slidra project

//! Golden-fixture tests for the crate's pure-function public API — the
//! second of the three public boundaries this ticket tests at (plan section
//! 6.2): `slidra` the library's exported functions, fed fixtures whose
//! expected values were generated by actually running the real TypeScript
//! implementation (`scripts/gen-golden.mjs`), never by hand-computing or
//! capturing this Rust port's own output.
//!
//! Regenerate fixtures with `node scripts/gen-golden.mjs` after building
//! `packages/core` (`npm run build --workspace=packages/core`); this test
//! file only reads `tests/golden/*.json`, it never regenerates them
//! (network/`packages/core` build tooling aren't guaranteed available
//! wherever `cargo test` runs).

use serde::Deserialize;
use slidra::geometry::bbox::{
    ElementBoundsOptions, TextBoundsContext, element_bounds, format_bbox, path_bounds,
    primitive_bounds,
};
use slidra::geometry::transform::IDENTITY;
use slidra::media_format::{MediaKind, detect_media_format};
use slidra::slide::format::{SlideElement, SlideElementKind, SlidePrimitive, TextAlign};
use slidra::slide::scan::{ScannedNode, scan_document};
use slidra::slide::table_grid::TableGrid;
use slidra::svgnum::format_svg_number;
use slidra::text::font::{DEFAULT_FONT_BYTES, FontMetrics, parse_font};
use slidra::text::metrics::measure_text_width;
use slidra::text::render::render_text_box_content;
use slidra::text::wrap::{Align, WrapOptions, wrap_text};
use std::collections::{BTreeMap, HashMap};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn golden_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/golden")
        .join(name)
}

#[derive(Deserialize)]
struct SvgNumberCase {
    input: f64,
    expected: String,
}

#[test]
fn svgnum_matches_ts_reference_for_every_golden_case() {
    let raw = fs::read_to_string(golden_path("svgnum.json"))
        .expect("tests/golden/svgnum.json must exist — run `node scripts/gen-golden.mjs`");
    let cases: Vec<SvgNumberCase> =
        serde_json::from_str(&raw).expect("golden file must be valid JSON");
    assert!(
        cases.len() >= 200,
        "plan AC9 requires >= 200 svgnum golden cases, found {}",
        cases.len()
    );

    let mut failures = Vec::new();
    for case in &cases {
        let actual = format_svg_number(case.input);
        if actual != case.expected {
            failures.push(format!(
                "input={} expected={:?} actual={:?}",
                case.input, case.expected, actual
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "svgnum mismatches against TS golden data:\n{}",
        failures.join("\n")
    );
}

#[derive(Deserialize)]
struct TextWrapFixtureInput {
    text: String,
    width: f64,
    #[serde(rename = "fontSizePx")]
    font_size_px: f64,
}

#[derive(Deserialize)]
struct TextWrapFixture {
    input: TextWrapFixtureInput,
    #[serde(rename = "expectedInnerMarkup")]
    expected_inner_markup: String,
    #[serde(rename = "expectedTextHeight")]
    expected_text_height: String,
}

/// The exact fixture from the implementation plan (NOOP-277 section 5, AC9):
/// a two-paragraph CJK+ASCII string wrapped at width 300 / font-size 24,
/// run end-to-end through the real CLI (`slidra textbox add`) and
/// captured by `scripts/gen-golden.mjs`. This is the single most
/// load-bearing golden case in this ticket — it exercises wrap.rs, render.rs,
/// runs.rs (empty-runs path), font.rs (real embedded TTF: cmap/hmtx/GSUB),
/// and svgnum.rs together, matching how they're actually used in
/// combination rather than only in isolation.
#[test]
fn text_wrap_and_render_matches_ts_reference_fixture() {
    let raw = fs::read_to_string(golden_path("text_wrap_fixture.json")).expect(
        "tests/golden/text_wrap_fixture.json must exist — run `node scripts/gen-golden.mjs`",
    );
    let fixture: TextWrapFixture =
        serde_json::from_str(&raw).expect("golden file must be valid JSON");

    let font = parse_font(DEFAULT_FONT_BYTES).expect("embedded default font must parse");
    let options = WrapOptions {
        width: fixture.input.width,
        font: &font,
        font_size_px: fixture.input.font_size_px,
        align: Align::Left,
        indents: None,
    };

    let wrapped =
        wrap_text(&fixture.input.text, &options).expect("fixture text must wrap without error");
    let markup = render_text_box_content(&wrapped.lines, &[]);
    let height = format_svg_number(wrapped.height);

    assert_eq!(
        markup, fixture.expected_inner_markup,
        "rendered <tspan> markup diverges from the TS-generated golden fixture"
    );
    assert_eq!(
        height, fixture.expected_text_height,
        "text-box height diverges from the TS-generated golden fixture"
    );
}

// --- scan.json --------------------------------------------------------
//
// NOOP-292 (Review round 1, NOOP-283, FAIL item 1): scan.rs had no golden
// coverage at all — its 18 hand-written tests were self-verified by the
// same porting pass that wrote the code under test. These cases run the
// real `scanDocument` (`scripts/gen-golden.mjs`'s `genScan`), covering the
// module's four rules plus one case per distinct error message.

#[derive(Deserialize)]
struct ScanAttributeCase {
    name: String,
    value: String,
    start: usize,
    end: usize,
}

#[derive(Deserialize)]
struct ScanNodeCase {
    tag: String,
    attributes: Vec<ScanAttributeCase>,
    start: usize,
    end: usize,
    #[serde(rename = "contentStart")]
    content_start: usize,
    #[serde(rename = "contentEnd")]
    content_end: usize,
    #[serde(rename = "selfClosing")]
    self_closing: bool,
    children: Vec<ScanNodeCase>,
}

#[derive(Deserialize)]
struct ScanTreeCase {
    label: String,
    svg: String,
    expected: Vec<ScanNodeCase>,
}

#[derive(Deserialize)]
struct ScanErrorCase {
    label: String,
    svg: String,
    #[serde(rename = "expectedMessage")]
    expected_message: String,
}

#[derive(Deserialize)]
struct ScanGolden {
    tree: Vec<ScanTreeCase>,
    errors: Vec<ScanErrorCase>,
}

fn assert_scan_node_matches(actual: &ScannedNode, expected: &ScanNodeCase, path: &str) {
    assert_eq!(actual.tag, expected.tag, "{path}: tag mismatch");
    assert_eq!(actual.start, expected.start, "{path}: start mismatch");
    assert_eq!(actual.end, expected.end, "{path}: end mismatch");
    assert_eq!(
        actual.content_start, expected.content_start,
        "{path}: contentStart mismatch"
    );
    assert_eq!(
        actual.content_end, expected.content_end,
        "{path}: contentEnd mismatch"
    );
    assert_eq!(
        actual.self_closing, expected.self_closing,
        "{path}: selfClosing mismatch"
    );
    assert_eq!(
        actual.attributes.len(),
        expected.attributes.len(),
        "{path}: attribute count mismatch"
    );
    for (i, (a, e)) in actual
        .attributes
        .iter()
        .zip(expected.attributes.iter())
        .enumerate()
    {
        assert_eq!(a.name, e.name, "{path}: attribute[{i}].name mismatch");
        assert_eq!(a.value, e.value, "{path}: attribute[{i}].value mismatch");
        assert_eq!(a.start, e.start, "{path}: attribute[{i}].start mismatch");
        assert_eq!(a.end, e.end, "{path}: attribute[{i}].end mismatch");
    }
    assert_eq!(
        actual.children.len(),
        expected.children.len(),
        "{path}: children count mismatch"
    );
    for (i, (a, e)) in actual
        .children
        .iter()
        .zip(expected.children.iter())
        .enumerate()
    {
        assert_scan_node_matches(a, e, &format!("{path}/children[{i}]"));
    }
}

#[test]
fn scan_document_matches_ts_reference_tree_and_error_cases() {
    let raw = fs::read_to_string(golden_path("scan.json"))
        .expect("tests/golden/scan.json must exist — run `node scripts/gen-golden.mjs`");
    let golden: ScanGolden = serde_json::from_str(&raw).expect("golden file must be valid JSON");

    for case in &golden.tree {
        let actual = scan_document(&case.svg).unwrap_or_else(|err| {
            panic!(
                "case {:?}: expected scan_document to succeed, got {:?}",
                case.label,
                err.message()
            )
        });
        assert_eq!(
            actual.len(),
            case.expected.len(),
            "case {:?}: top-level node count mismatch",
            case.label
        );
        for (i, (a, e)) in actual.iter().zip(case.expected.iter()).enumerate() {
            assert_scan_node_matches(a, e, &format!("case {:?} [{}]", case.label, i));
        }
    }

    for case in &golden.errors {
        let err = scan_document(&case.svg).expect_err(&format!(
            "case {:?}: expected scan_document to fail",
            case.label
        ));
        assert_eq!(
            err.message(),
            case.expected_message,
            "case {:?}: error message mismatch",
            case.label
        );
    }
}

// --- bbox.json ----------------------------------------------------------
//
// NOOP-292 (Review round 1, NOOP-283, FAIL item 1): one golden case per
// primitive/element kind plan A9 requires — rect/ellipse/line/path
// (including the elliptical-arc rejection)/group/table/text — each
// compared as its four `format_svg_number` fields, run through the real
// `primitiveBounds`/`elementBounds`/`pathBounds` (`scripts/gen-golden.mjs`'s
// `genBbox`).

#[derive(Deserialize)]
struct FormattedRectCase {
    x: String,
    y: String,
    width: String,
    height: String,
}

#[derive(Deserialize)]
struct BboxPrimitiveCase {
    label: String,
    tag: String,
    attrs: HashMap<String, String>,
    expected: FormattedRectCase,
}

#[derive(Deserialize)]
struct BboxPathOkCase {
    label: String,
    d: String,
    expected: FormattedRectCase,
}

#[derive(Deserialize)]
struct BboxPathArcCase {
    label: String,
    d: String,
    #[serde(rename = "expectedError")]
    expected_error: String,
}

#[derive(Deserialize)]
struct BboxPathCases {
    ok: BboxPathOkCase,
    #[serde(rename = "arcRejected")]
    arc_rejected: BboxPathArcCase,
}

#[derive(Deserialize)]
struct BboxGroupCase {
    label: String,
    expected: FormattedRectCase,
}

#[derive(Deserialize)]
struct BboxTableCase {
    label: String,
    cols: Vec<f64>,
    rows: Vec<f64>,
    expected: FormattedRectCase,
}

#[derive(Deserialize)]
struct BboxTextCase {
    label: String,
    attrs: HashMap<String, String>,
    text: String,
    expected: FormattedRectCase,
}

#[derive(Deserialize)]
struct BboxGolden {
    primitives: Vec<BboxPrimitiveCase>,
    path: BboxPathCases,
    group: BboxGroupCase,
    table: BboxTableCase,
    text: BboxTextCase,
}

fn primitive_from_attrs(tag: &str, attrs: &HashMap<String, String>) -> SlidePrimitive {
    SlidePrimitive {
        tag: tag.to_string(),
        attrs: attrs.iter().map(|(k, v)| (k.clone(), v.clone())).collect(),
        text: String::new(),
        tspan_count: 0,
        runs: Vec::new(),
    }
}

fn bbox_leaf_element(
    id: &str,
    kind: SlideElementKind,
    primitives: Vec<SlidePrimitive>,
) -> SlideElement {
    SlideElement {
        id: id.to_string(),
        name: None,
        media: None,
        kind,
        transform: None,
        matrix: IDENTITY,
        children: Vec::new(),
        primitives,
        text_width: None,
        text_height: None,
        text_align: TextAlign::Left,
        table: None,
    }
}

fn assert_formatted_rect_eq(
    actual: &slidra::geometry::bbox::FormattedBbox,
    expected: &FormattedRectCase,
    label: &str,
) {
    assert_eq!(actual.x, expected.x, "{label}: x mismatch");
    assert_eq!(actual.y, expected.y, "{label}: y mismatch");
    assert_eq!(actual.width, expected.width, "{label}: width mismatch");
    assert_eq!(actual.height, expected.height, "{label}: height mismatch");
}

#[test]
fn bbox_matches_ts_reference_for_every_primitive_and_element_kind() {
    let raw = fs::read_to_string(golden_path("bbox.json"))
        .expect("tests/golden/bbox.json must exist — run `node scripts/gen-golden.mjs`");
    let golden: BboxGolden = serde_json::from_str(&raw).expect("golden file must be valid JSON");

    for case in &golden.primitives {
        let primitive = primitive_from_attrs(&case.tag, &case.attrs);
        let bbox = primitive_bounds(&primitive, None)
            .unwrap_or_else(|err| panic!("case {:?}: {:?}", case.label, err.message()));
        assert_formatted_rect_eq(&format_bbox(&bbox), &case.expected, &case.label);
    }

    let ok_bbox = path_bounds(&golden.path.ok.d).expect("path-cubic-bezier case must succeed");
    assert_formatted_rect_eq(
        &format_bbox(&ok_bbox),
        &golden.path.ok.expected,
        &golden.path.ok.label,
    );

    let arc_err = path_bounds(&golden.path.arc_rejected.d).expect_err("arc path must be rejected");
    assert_eq!(
        arc_err.message(),
        golden.path.arc_rejected.expected_error,
        "case {:?}: arc rejection message mismatch",
        golden.path.arc_rejected.label
    );

    // group: union of two children's transformed boxes.
    let child_a = bbox_leaf_element(
        "child-a",
        SlideElementKind::Rect,
        vec![primitive_from_attrs(
            "rect",
            &HashMap::from([
                ("x".to_string(), "2".to_string()),
                ("y".to_string(), "3".to_string()),
                ("width".to_string(), "8".to_string()),
                ("height".to_string(), "6".to_string()),
            ]),
        )],
    );
    let child_b = bbox_leaf_element(
        "child-b",
        SlideElementKind::Ellipse,
        vec![primitive_from_attrs(
            "ellipse",
            &HashMap::from([
                ("cx".to_string(), "30".to_string()),
                ("cy".to_string(), "10".to_string()),
                ("rx".to_string(), "4".to_string()),
                ("ry".to_string(), "2".to_string()),
            ]),
        )],
    );
    let mut group = bbox_leaf_element("group-1", SlideElementKind::Group, Vec::new());
    group.children = vec![child_a, child_b];
    let options = ElementBoundsOptions {
        ancestors: &[],
        fonts: None,
    };
    let group_bbox = element_bounds(&group, &options).expect("group bbox must succeed");
    assert_formatted_rect_eq(
        &format_bbox(&group_bbox),
        &golden.group.expected,
        &golden.group.label,
    );

    // table: declared grid extent, not a primitive union.
    let mut table_element = bbox_leaf_element("table-1", SlideElementKind::Table, Vec::new());
    table_element.table = Some(TableGrid {
        cols: golden.table.cols.clone(),
        rows: golden.table.rows.clone(),
    });
    let table_bbox = element_bounds(&table_element, &options).expect("table bbox must succeed");
    assert_formatted_rect_eq(
        &format_bbox(&table_bbox),
        &golden.table.expected,
        &golden.table.label,
    );

    // text: a plain `<text>` (no tspans), measured via the real embedded
    // default font — the same physical .ttf `packages/core/dist`'s
    // `parseFont` read to produce this golden fixture.
    let font = parse_font(DEFAULT_FONT_BYTES).expect("embedded default font must parse");
    let fonts: HashMap<String, Box<dyn FontMetrics>> = HashMap::from([(
        "Noto Sans TC".to_string(),
        Box::new(font) as Box<dyn FontMetrics>,
    )]);
    let text_primitive = SlidePrimitive {
        text: golden.text.text.clone(),
        ..primitive_from_attrs("text", &golden.text.attrs)
    };
    let text_context = TextBoundsContext {
        fonts: &fonts,
        text_width: None,
        text_height: None,
        element_id: "text-1".to_string(),
    };
    let text_bbox =
        primitive_bounds(&text_primitive, Some(&text_context)).expect("text bbox must succeed");
    assert_formatted_rect_eq(
        &format_bbox(&text_bbox),
        &golden.text.expected,
        &golden.text.label,
    );
}

// --- font.json ------------------------------------------------------------
//
// NOOP-292 (Review round 1, NOOP-283, FAIL item 1): `parseFont`'s line
// metrics plus >= 50 `measureTextWidth` golden cases, run against the real
// bundled font (`scripts/gen-golden.mjs`'s `genFont`) — font.rs and
// metrics.rs had no golden coverage at all before this.

#[derive(Deserialize)]
struct FontMetricsCase {
    #[serde(rename = "unitsPerEm")]
    units_per_em: u16,
    ascender: i16,
    descender: i16,
    #[serde(rename = "lineGap")]
    line_gap: i16,
}

#[derive(Deserialize)]
struct MeasureTextWidthCase {
    text: String,
    #[serde(rename = "fontSizePx")]
    font_size_px: f64,
    expected: String,
}

#[derive(Deserialize)]
struct FontGolden {
    metrics: FontMetricsCase,
    #[serde(rename = "measureTextWidth")]
    measure_text_width: Vec<MeasureTextWidthCase>,
}

#[test]
fn font_metrics_and_measure_text_width_match_ts_reference() {
    let raw = fs::read_to_string(golden_path("font.json"))
        .expect("tests/golden/font.json must exist — run `node scripts/gen-golden.mjs`");
    let golden: FontGolden = serde_json::from_str(&raw).expect("golden file must be valid JSON");
    assert!(
        golden.measure_text_width.len() >= 50,
        "plan A9 requires >= 50 measureTextWidth golden cases, found {}",
        golden.measure_text_width.len()
    );

    let font = parse_font(DEFAULT_FONT_BYTES).expect("embedded default font must parse");
    assert_eq!(
        font.units_per_em(),
        golden.metrics.units_per_em,
        "unitsPerEm mismatch"
    );
    assert_eq!(
        font.ascender(),
        golden.metrics.ascender,
        "ascender mismatch"
    );
    assert_eq!(
        font.descender(),
        golden.metrics.descender,
        "descender mismatch"
    );
    assert_eq!(font.line_gap(), golden.metrics.line_gap, "lineGap mismatch");

    let mut failures = Vec::new();
    for case in &golden.measure_text_width {
        let actual = measure_text_width(&font, &case.text, case.font_size_px)
            .unwrap_or_else(|err| panic!("text={:?}: {:?}", case.text, err.message()));
        let formatted = format_svg_number(actual);
        if formatted != case.expected {
            failures.push(format!(
                "text={:?} fontSizePx={} expected={:?} actual={:?}",
                case.text, case.font_size_px, case.expected, formatted
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "measureTextWidth mismatches against TS golden data:\n{}",
        failures.join("\n")
    );
}

// --- text_wrap_extra_cases.json --------------------------------------------
//
// NOOP-292 (Review round 1, NOOP-283, FAIL item 1): the plan's single
// `text_wrap_fixture` (full CLI round trip) doesn't cover CJK-only,
// ASCII-only, an explicit hard break, list-paragraph indents, a single word
// wider than the box, or an empty paragraph. These six run
// `wrapText`/`renderTextBoxContent` directly against the real bundled font
// (`scripts/gen-golden.mjs`'s `genTextWrapExtraCases`).

#[derive(Deserialize)]
struct TextWrapExtraInput {
    text: String,
    width: f64,
    #[serde(rename = "fontSizePx")]
    font_size_px: f64,
    #[serde(default)]
    indents: Option<Vec<f64>>,
}

#[derive(Deserialize)]
struct TextWrapExtraCase {
    label: String,
    input: TextWrapExtraInput,
    #[serde(rename = "expectedInnerMarkup")]
    expected_inner_markup: String,
    #[serde(rename = "expectedTextHeight")]
    expected_text_height: String,
}

#[test]
fn text_wrap_extra_cases_match_ts_reference() {
    let raw = fs::read_to_string(golden_path("text_wrap_extra_cases.json")).expect(
        "tests/golden/text_wrap_extra_cases.json must exist — run `node scripts/gen-golden.mjs`",
    );
    let cases: Vec<TextWrapExtraCase> =
        serde_json::from_str(&raw).expect("golden file must be valid JSON");
    assert!(
        cases.len() >= 6,
        "plan NOOP-292 requires >= 6 supplementary text-wrap golden cases, found {}",
        cases.len()
    );

    let font = parse_font(DEFAULT_FONT_BYTES).expect("embedded default font must parse");
    let mut failures = Vec::new();
    for case in &cases {
        let options = WrapOptions {
            width: case.input.width,
            font: &font,
            font_size_px: case.input.font_size_px,
            align: Align::Left,
            indents: case.input.indents.as_deref(),
        };
        let wrapped = wrap_text(&case.input.text, &options)
            .unwrap_or_else(|err| panic!("case {:?}: {:?}", case.label, err.message()));
        let markup = render_text_box_content(&wrapped.lines, &[]);
        let height = format_svg_number(wrapped.height);
        if markup != case.expected_inner_markup || height != case.expected_text_height {
            failures.push(format!(
                "case={:?}\n  expected_markup={:?}\n  actual_markup={:?}\n  expected_height={:?}\n  actual_height={:?}",
                case.label, case.expected_inner_markup, markup, case.expected_text_height, height
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "text-wrap extra-case mismatches against TS golden data:\n{}",
        failures.join("\n")
    );
}

// ---------------------------------------------------------------------------
// [E4.T4] A2: every repo `project.json` fixture is already at `formatVersion`
// 1 (there is no migration chain any more), and `pack` -> `open` round-trips
// the content exactly (plan §5 A2). Not a TS-golden comparison — a
// self-contained Rust integration test over the crate's own `container`
// public API, hence living here (boundary 2) rather than in `cli_golden.rs`
// (a CLI process boundary these functions are underneath).
// ---------------------------------------------------------------------------

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("repo root must exist")
}

/// Every directory under `docs/demo/`, `e2e/fixtures/*/`, `qa/fixtures/skills/*/`
/// that has its own `project.json` — 27 as of this ticket (§5 A2's own
/// count, re-derived here rather than hard-coded so a fixture added later
/// is picked up automatically).
fn fixture_directories() -> Vec<PathBuf> {
    let root = repo_root();
    let mut dirs = Vec::new();
    for top in ["docs/demo", "e2e/fixtures", "qa/fixtures/skills"] {
        let top_path = root.join(top);
        if top_path.join("project.json").is_file() {
            dirs.push(top_path.clone());
        }
        let Ok(entries) = fs::read_dir(&top_path) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() && path.join("project.json").is_file() {
                dirs.push(path);
            }
        }
    }
    dirs
}

/// Recursively collects every file under `dir` into a `relative path (POSIX
/// separators) -> bytes` map — the "equivalence" this test and A2 both use:
/// the zip container's own bytes are never compared (compression level is
/// not part of the format), only the fully-unpacked content mapping.
fn collect_tree(dir: &Path) -> BTreeMap<String, Vec<u8>> {
    fn walk(root: &Path, current: &Path, into: &mut BTreeMap<String, Vec<u8>>) {
        for entry in fs::read_dir(current).unwrap().flatten() {
            let path = entry.path();
            if path.is_dir() {
                walk(root, &path, into);
            } else if path.is_file() {
                let relative = path
                    .strip_prefix(root)
                    .unwrap()
                    .to_string_lossy()
                    .replace('\\', "/");
                into.insert(relative, fs::read(&path).unwrap());
            }
        }
    }
    let mut map = BTreeMap::new();
    walk(dir, dir, &mut map);
    map
}

fn temp_dir(label: &str) -> PathBuf {
    let dir = env::temp_dir().join(format!("slidra-unit-golden-{label}-{}", std::process::id()));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).unwrap();
    dir
}

/// Zips `source_dir` into a legacy (pre-SQLite) `.slidra` container at
/// `output_path` — every repo fixture is a plain directory, not a file, so
/// this test builds the "v1-v4 file a real author would have on disk"
/// itself before handing it to `deck::migrate_legacy_zip_in_place`. Mirrors
/// the shape the deleted `container::pack_directory` used to produce
/// (`slides/`/`assets`/`fonts` present even when empty), since that is
/// what a legacy `.slidra` actually looked like.
fn zip_legacy_directory(source_dir: &Path, output_path: &Path) {
    let tree = collect_tree(source_dir);
    let mut buffer: Vec<u8> = Vec::new();
    {
        let mut writer = zip::ZipWriter::new(std::io::Cursor::new(&mut buffer));
        let options: zip::write::FileOptions<'_, ()> = zip::write::FileOptions::default();
        for dir in ["slides/", "assets/", "fonts/"] {
            writer.add_directory(dir, options).unwrap();
        }
        for (path, bytes) in &tree {
            writer.start_file(path, options).unwrap();
            std::io::Write::write_all(&mut writer, bytes).unwrap();
        }
        writer.finish().unwrap();
    }
    fs::write(output_path, &buffer).unwrap();
}

/// Snapshots a deck's entire content as a "virtual path -> bytes" map, via
/// the same public read API production code uses — the SQLite-backed
/// equivalent of `collect_tree`'s real-directory walk.
fn collect_deck_tree(deck_path: &Path) -> BTreeMap<String, Vec<u8>> {
    let mut map = BTreeMap::new();
    for path in slidra::workspace::virtual_fs::list_virtual_files(deck_path, "").unwrap() {
        let bytes =
            slidra::workspace::virtual_fs::read_virtual_file_bytes(deck_path, &path).unwrap();
        map.insert(path, bytes);
    }
    map
}

#[test]
fn every_repo_fixture_migrates_to_formatversion_5_with_content_preserved() {
    let dirs = fixture_directories();
    assert_eq!(
        dirs.len(),
        28,
        "expected exactly 28 project.json fixtures under docs/demo, e2e/fixtures, qa/fixtures/skills, found {}",
        dirs.len()
    );

    let scratch = temp_dir("fixture-migration");
    let mut failures = Vec::new();

    for (i, source_dir) in dirs.iter().enumerate() {
        let legacy_path = scratch.join(format!("{i}-legacy.slidra"));
        zip_legacy_directory(source_dir, &legacy_path);

        if let Err(err) = slidra::deck::migrate_legacy_zip_in_place(&legacy_path) {
            failures.push(format!(
                "{}: migration failed: {}",
                source_dir.display(),
                err.message()
            ));
            continue;
        }

        let project = match slidra::workspace::project::read_project_json(&legacy_path) {
            Ok(p) => p,
            Err(err) => {
                failures.push(format!(
                    "{}: could not read migrated project.json: {}",
                    source_dir.display(),
                    err.message()
                ));
                continue;
            }
        };
        if project.format_version != 5.0 {
            failures.push(format!(
                "{}: formatVersion is {:?}, not 5",
                source_dir.display(),
                project.format_version
            ));
        }

        // Content preserved exactly, except `project.json`'s own
        // `formatVersion` field (the one deliberate bump migration makes —
        // every other field, and every other file, must be byte-identical).
        let original_tree = collect_tree(source_dir);
        let migrated_tree = collect_deck_tree(&legacy_path);
        for (path, original_bytes) in &original_tree {
            let Some(migrated_bytes) = migrated_tree.get(path) else {
                failures.push(format!(
                    "{}: {path} missing after migration",
                    source_dir.display()
                ));
                continue;
            };
            if path == "project.json" {
                let mut original_json: serde_json::Value =
                    serde_json::from_slice(original_bytes).unwrap();
                let mut migrated_json: serde_json::Value =
                    serde_json::from_slice(migrated_bytes).unwrap();
                original_json["formatVersion"] = serde_json::json!(5);
                migrated_json["formatVersion"] = serde_json::json!(5);
                if original_json != migrated_json {
                    failures.push(format!(
                        "{}: project.json diverged beyond formatVersion",
                        source_dir.display()
                    ));
                }
                continue;
            }
            if migrated_bytes != original_bytes {
                failures.push(format!("{}: {path} content diverged", source_dir.display()));
            }
        }
        let only_in_migrated: Vec<&String> = migrated_tree
            .keys()
            .filter(|k| !original_tree.contains_key(*k))
            .collect();
        if !only_in_migrated.is_empty() {
            failures.push(format!(
                "{}: migration introduced unexpected files: {only_in_migrated:?}",
                source_dir.display()
            ));
        }

        // Idempotence: migrating an already-SQLite deck a second time must
        // be a byte-for-byte no-op.
        let before = fs::read(&legacy_path).unwrap();
        slidra::deck::migrate_legacy_zip_in_place(&legacy_path).unwrap();
        let after = fs::read(&legacy_path).unwrap();
        if before != after {
            failures.push(format!(
                "{}: re-migrating an already-SQLite deck was not a no-op",
                source_dir.display()
            ));
        }
    }

    fs::remove_dir_all(&scratch).ok();
    assert!(
        failures.is_empty(),
        "migration fixture failures:\n{}",
        failures.join("\n")
    );
}

#[derive(Deserialize)]
struct MediaFormatExpected {
    #[serde(rename = "mimeType")]
    mime_type: String,
    kind: String,
    #[serde(rename = "aliasExtensions")]
    alias_extensions: Vec<String>,
    extension: String,
}

#[derive(Deserialize)]
struct MediaFormatCase {
    label: String,
    bytes: Vec<u8>,
    expected: Option<MediaFormatExpected>,
}

/// Acceptance criterion A9: `detect_media_format` against every golden
/// case's REAL `detectMediaFormat` (TS) output, not this port's own
/// reasoning about what the TS behavior should be — the fixture generator
/// imports and calls the actual `packages/core/dist/media-format.js`.
#[test]
fn media_format_matches_ts_reference_for_every_golden_case() {
    let raw = fs::read_to_string(golden_path("media_format.json"))
        .expect("tests/golden/media_format.json must exist — run `node scripts/gen-golden.mjs`");
    let cases: Vec<MediaFormatCase> =
        serde_json::from_str(&raw).expect("golden file must be valid JSON");
    assert!(
        cases.len() >= 15,
        "expected at least one golden case per recognised format, found {}",
        cases.len()
    );

    let mut failures = Vec::new();
    for case in &cases {
        let actual = detect_media_format(&case.bytes);
        match (&case.expected, actual) {
            (None, None) => {}
            (Some(expected), Some(actual)) => {
                let kind_str = match actual.kind {
                    MediaKind::Image => "image",
                    MediaKind::Video => "video",
                    MediaKind::Audio => "audio",
                };
                let alias: Vec<String> = actual
                    .alias_extensions
                    .iter()
                    .map(|s| s.to_string())
                    .collect();
                if expected.extension != actual.extension
                    || expected.mime_type != actual.mime_type
                    || expected.kind != kind_str
                    || expected.alias_extensions != alias
                {
                    failures.push(format!(
                        "case={:?}: expected {}/{}/{}/{:?}, got {}/{}/{}/{:?}",
                        case.label,
                        expected.extension,
                        expected.mime_type,
                        expected.kind,
                        expected.alias_extensions,
                        actual.extension,
                        actual.mime_type,
                        kind_str,
                        alias
                    ));
                }
            }
            (expected, actual) => {
                failures.push(format!(
                    "case={:?}: expected {:?}, got {:?}",
                    case.label,
                    expected.is_some(),
                    actual.is_some()
                ));
            }
        }
    }
    assert!(
        failures.is_empty(),
        "media_format mismatches against TS golden data:\n{}",
        failures.join("\n")
    );
}

// --- element_commands.json --------------------------------------------
//
// NOOP-309 (Execute round 2, P9): one golden case per command in the
// ticket's 29-command scope (`element *`, `text *`, `textbox *`,
// `comment *`), run through the REAL functions in
// `packages/core/dist/element-*.js`/`slide/comments.js`
// (`scripts/gen-golden.mjs`'s `genElementCommands`). `element
// copy`/`cut`/`paste`/`duplicate` are covered here as their own pure
// primitives (`extractElementsForCopy`/`deleteElements`/`pasteElements`);
// the 4-directional CLI-level clipboard interop (internal-file and
// `--svg-file` round trips both directions) is `cli_golden.rs`'s job (plan
// section 6.1, layer 1), not this file's.

use slidra::element::arrange::{self, AlignDirection, DistributeAxis};
use slidra::element::clipboard::{self, ClipboardPayload};
use slidra::element::edit::{
    self, InsertElementInput, InsertElementKind, OrderDirection, ResizeAnchor,
};
use slidra::element::group;
use slidra::element::text::{self, AddTextBoxInput, TextStyleUpdate};
use slidra::slide::comments::{self, SlideComment};
use slidra::text::list::ListKind;

type JsonValue = serde_json::Value;

/// Matches `scripts/gen-golden.mjs`'s own `SLIDE_PATH` constant — only used
/// for error-message interpolation by `assert_slide_compliant`, never
/// parsed, so any value both engines agree on is fine.
const GOLDEN_SLIDE_PATH: &str = "slides/001.svg";

#[derive(Deserialize)]
struct ElementCommandCase {
    command: String,
    label: String,
    fixture: String,
    args: JsonValue,
    expected: JsonValue,
}

fn golden_font_book() -> HashMap<String, Box<dyn FontMetrics>> {
    let font = parse_font(DEFAULT_FONT_BYTES).expect("embedded default font must parse");
    HashMap::from([(
        "Noto Sans TC".to_string(),
        Box::new(font) as Box<dyn FontMetrics>,
    )])
}

fn arg_str<'a>(args: &'a JsonValue, key: &str) -> &'a str {
    args.get(key)
        .and_then(|v| v.as_str())
        .unwrap_or_else(|| panic!("golden case missing string arg {key:?}"))
}

fn arg_opt_str<'a>(args: &'a JsonValue, key: &str) -> Option<&'a str> {
    args.get(key).and_then(|v| v.as_str())
}

fn arg_f64(args: &JsonValue, key: &str) -> f64 {
    args.get(key)
        .and_then(|v| v.as_f64())
        .unwrap_or_else(|| panic!("golden case missing number arg {key:?}"))
}

fn arg_opt_f64(args: &JsonValue, key: &str) -> Option<f64> {
    args.get(key).and_then(|v| v.as_f64())
}

fn arg_usize(args: &JsonValue, key: &str) -> usize {
    args.get(key)
        .and_then(|v| v.as_u64())
        .unwrap_or_else(|| panic!("golden case missing integer arg {key:?}")) as usize
}

fn arg_str_vec(args: &JsonValue, key: &str) -> Vec<String> {
    args.get(key)
        .and_then(|v| v.as_array())
        .unwrap_or_else(|| panic!("golden case missing array arg {key:?}"))
        .iter()
        .map(|v| {
            v.as_str()
                .expect("array element must be a string")
                .to_string()
        })
        .collect()
}

fn parse_order_direction(raw: &str) -> OrderDirection {
    match raw {
        "front" => OrderDirection::Front,
        "back" => OrderDirection::Back,
        "up" => OrderDirection::Up,
        "down" => OrderDirection::Down,
        other => panic!("unknown order direction in golden fixture: {other}"),
    }
}

fn parse_align_direction(raw: &str) -> AlignDirection {
    match raw {
        "left" => AlignDirection::Left,
        "hcenter" => AlignDirection::HCenter,
        "right" => AlignDirection::Right,
        "top" => AlignDirection::Top,
        "vcenter" => AlignDirection::VCenter,
        "bottom" => AlignDirection::Bottom,
        other => panic!("unknown align direction in golden fixture: {other}"),
    }
}

fn parse_distribute_axis(raw: &str) -> DistributeAxis {
    match raw {
        "horizontal" => DistributeAxis::Horizontal,
        "vertical" => DistributeAxis::Vertical,
        other => panic!("unknown distribute axis in golden fixture: {other}"),
    }
}

fn parse_resize_anchor(raw: &str) -> ResizeAnchor {
    match raw {
        "nw" => ResizeAnchor::Nw,
        "ne" => ResizeAnchor::Ne,
        "sw" => ResizeAnchor::Sw,
        "se" => ResizeAnchor::Se,
        other => panic!("unknown resize anchor in golden fixture: {other}"),
    }
}

fn parse_insert_kind(raw: &str) -> InsertElementKind {
    match raw {
        "rect" => InsertElementKind::Rect,
        "ellipse" => InsertElementKind::Ellipse,
        "line" => InsertElementKind::Line,
        "image" => InsertElementKind::Image,
        "path" => InsertElementKind::Path,
        "video" => InsertElementKind::Video,
        "audio" => InsertElementKind::Audio,
        other => panic!("unknown insert kind in golden fixture: {other}"),
    }
}

fn parse_text_align(raw: &str) -> TextAlign {
    match raw {
        "left" => TextAlign::Left,
        "center" => TextAlign::Center,
        "right" => TextAlign::Right,
        other => panic!("unknown text align in golden fixture: {other}"),
    }
}

fn parse_list_kind(raw: &str) -> ListKind {
    match raw {
        "bullet" => ListKind::Bullet,
        "number" => ListKind::Number,
        "none" => ListKind::None,
        other => panic!("unknown list kind in golden fixture: {other}"),
    }
}

fn comment_from_json(value: &JsonValue) -> SlideComment {
    SlideComment {
        id: value["id"].as_str().expect("comment.id").to_string(),
        target: value["target"]
            .as_str()
            .expect("comment.target")
            .to_string(),
        author: value["author"]
            .as_str()
            .expect("comment.author")
            .to_string(),
        created: value["created"]
            .as_str()
            .expect("comment.created")
            .to_string(),
        text: value["text"].as_str().expect("comment.text").to_string(),
    }
}

enum CaseOutcome {
    Text(String),
    Comments(Vec<SlideComment>),
}

fn run_element_command_case(case: &ElementCommandCase) -> CaseOutcome {
    let args = &case.args;
    let svg = case.fixture.as_str();
    match case.command.as_str() {
        "element insert" => {
            let input = InsertElementInput {
                x: arg_opt_f64(args, "x"),
                y: arg_opt_f64(args, "y"),
                width: arg_opt_f64(args, "width"),
                height: arg_opt_f64(args, "height"),
                x1: arg_opt_f64(args, "x1"),
                y1: arg_opt_f64(args, "y1"),
                x2: arg_opt_f64(args, "x2"),
                y2: arg_opt_f64(args, "y2"),
                d: arg_opt_str(args, "d").map(String::from),
                fill: arg_opt_str(args, "fill").map(String::from),
                stroke: arg_opt_str(args, "stroke").map(String::from),
                stroke_width: arg_opt_f64(args, "strokeWidth"),
                href: arg_opt_str(args, "href").map(String::from),
                media: arg_opt_str(args, "media").map(String::from),
                embed: arg_opt_str(args, "embed").map(String::from),
            };
            let kind = parse_insert_kind(arg_str(args, "kind"));
            let result = edit::insert_element(svg, GOLDEN_SLIDE_PATH, "el-new", &input, kind)
                .unwrap_or_else(|err| panic!("{}: {:?}", case.label, err.message()));
            CaseOutcome::Text(result)
        }
        "element delete" | "element cut" => {
            let ids = arg_str_vec(args, "elementIds");
            let result = edit::delete_elements(svg, GOLDEN_SLIDE_PATH, &ids)
                .unwrap_or_else(|err| panic!("{}: {:?}", case.label, err.message()));
            CaseOutcome::Text(result)
        }
        "element move" => {
            let ids = arg_str_vec(args, "elementIds");
            let dx = arg_f64(args, "dx");
            let dy = arg_f64(args, "dy");
            let result = edit::move_elements(svg, GOLDEN_SLIDE_PATH, &ids, dx, dy, false)
                .unwrap_or_else(|err| panic!("{}: {:?}", case.label, err.message()));
            CaseOutcome::Text(result)
        }
        "element rotate" => {
            let ids = arg_str_vec(args, "elementIds");
            let degrees = arg_f64(args, "degrees");
            let result = edit::rotate_elements(svg, GOLDEN_SLIDE_PATH, &ids, degrees, false)
                .unwrap_or_else(|err| panic!("{}: {:?}", case.label, err.message()));
            CaseOutcome::Text(result)
        }
        "element order" => {
            let ids = arg_str_vec(args, "elementIds");
            let direction = parse_order_direction(arg_str(args, "direction"));
            let result = edit::reorder_elements(svg, GOLDEN_SLIDE_PATH, &ids, direction, false)
                .unwrap_or_else(|err| panic!("{}: {:?}", case.label, err.message()));
            CaseOutcome::Text(result)
        }
        "element lock" => {
            let ids = arg_str_vec(args, "elementIds");
            let result = edit::lock_elements(svg, GOLDEN_SLIDE_PATH, &ids)
                .unwrap_or_else(|err| panic!("{}: {:?}", case.label, err.message()));
            CaseOutcome::Text(result)
        }
        "element unlock" => {
            let ids = arg_str_vec(args, "elementIds");
            let result = edit::unlock_elements(svg, GOLDEN_SLIDE_PATH, &ids)
                .unwrap_or_else(|err| panic!("{}: {:?}", case.label, err.message()));
            CaseOutcome::Text(result)
        }
        "element name set" => {
            let ids = arg_str_vec(args, "elementIds");
            let name = arg_str(args, "name");
            let result = group::set_element_name(svg, GOLDEN_SLIDE_PATH, &ids, name)
                .unwrap_or_else(|err| panic!("{}: {:?}", case.label, err.message()));
            CaseOutcome::Text(result)
        }
        "element group" => {
            let ids = arg_str_vec(args, "elementIds");
            let new_group_id = arg_str(args, "newGroupId");
            let result = group::group_elements(svg, GOLDEN_SLIDE_PATH, &ids, new_group_id)
                .unwrap_or_else(|err| panic!("{}: {:?}", case.label, err.message()));
            CaseOutcome::Text(result.svg)
        }
        "element ungroup" => {
            let ids = arg_str_vec(args, "elementIds");
            let result = group::ungroup_elements(svg, GOLDEN_SLIDE_PATH, &ids)
                .unwrap_or_else(|err| panic!("{}: {:?}", case.label, err.message()));
            CaseOutcome::Text(result.svg)
        }
        "element scale" => {
            let ids = arg_str_vec(args, "elementIds");
            let factor = arg_f64(args, "factor");
            let fonts = golden_font_book();
            let result = edit::scale_elements(svg, GOLDEN_SLIDE_PATH, &ids, factor, &fonts, false)
                .unwrap_or_else(|err| panic!("{}: {:?}", case.label, err.message()));
            CaseOutcome::Text(result)
        }
        "element resize" => {
            let ids = arg_str_vec(args, "elementIds");
            let width = arg_f64(args, "width");
            let height = arg_f64(args, "height");
            let anchor = parse_resize_anchor(arg_str(args, "anchor"));
            let fonts = golden_font_book();
            let result = edit::resize_elements(
                svg,
                GOLDEN_SLIDE_PATH,
                &ids,
                width,
                height,
                anchor,
                &fonts,
                false,
            )
            .unwrap_or_else(|err| panic!("{}: {:?}", case.label, err.message()));
            CaseOutcome::Text(result)
        }
        "element style set" => {
            let ids = arg_str_vec(args, "elementIds");
            let attr = arg_str(args, "attr");
            let value = arg_str(args, "value");
            let fonts = golden_font_book();
            let result =
                edit::set_element_style(svg, GOLDEN_SLIDE_PATH, &ids, attr, value, &fonts, false)
                    .unwrap_or_else(|err| panic!("{}: {:?}", case.label, err.message()));
            CaseOutcome::Text(result)
        }
        "element align" => {
            let ids = arg_str_vec(args, "elementIds");
            let direction = parse_align_direction(arg_str(args, "direction"));
            let fonts = golden_font_book();
            let result = arrange::align_elements(svg, GOLDEN_SLIDE_PATH, &ids, direction, &fonts)
                .unwrap_or_else(|err| panic!("{}: {:?}", case.label, err.message()));
            CaseOutcome::Text(result)
        }
        "element distribute" => {
            let ids = arg_str_vec(args, "elementIds");
            let axis = parse_distribute_axis(arg_str(args, "axis"));
            let fonts = golden_font_book();
            let result = arrange::distribute_elements(svg, GOLDEN_SLIDE_PATH, &ids, axis, &fonts)
                .unwrap_or_else(|err| panic!("{}: {:?}", case.label, err.message()));
            CaseOutcome::Text(result)
        }
        "text set" => {
            let element_id = arg_str(args, "elementId");
            let new_text = arg_str(args, "newText");
            let fonts = golden_font_book();
            let result = text::replace_element_text(svg, element_id, new_text, &fonts, false)
                .unwrap_or_else(|err| panic!("{}: {:?}", case.label, err.message()));
            CaseOutcome::Text(result)
        }
        "text style set" => {
            let element_id = arg_str(args, "elementId");
            let start = arg_usize(args, "rangeStart");
            let end = arg_usize(args, "rangeEnd");
            let update = TextStyleUpdate {
                font_weight: arg_opt_str(args, "fontWeight").map(String::from),
                font_style: arg_opt_str(args, "fontStyle").map(String::from),
            };
            let fonts = golden_font_book();
            let (result, _) =
                text::set_text_run_style(svg, element_id, start, end, &update, &fonts, false)
                    .unwrap_or_else(|err| panic!("{}: {:?}", case.label, err.message()));
            CaseOutcome::Text(result)
        }
        "text list set" => {
            let element_id = arg_str(args, "elementId");
            let paragraph = arg_usize(args, "paragraph");
            let kind = parse_list_kind(arg_str(args, "kind"));
            let fonts = golden_font_book();
            let (result, _) =
                text::set_paragraph_list(svg, element_id, paragraph, kind, &fonts, false)
                    .unwrap_or_else(|err| panic!("{}: {:?}", case.label, err.message()));
            CaseOutcome::Text(result)
        }
        "textbox add" => {
            let x = arg_f64(args, "x");
            let y = arg_f64(args, "y");
            let width = arg_f64(args, "width");
            let text_value = arg_str(args, "text");
            let font_size = arg_f64(args, "fontSize");
            let font_family = arg_str(args, "fontFamily");
            let align = parse_text_align(arg_str(args, "align"));
            let input = AddTextBoxInput {
                x,
                y,
                width,
                text: text_value,
                font_size,
                font_family,
                font_weight: arg_opt_f64(args, "fontWeight"),
                fill: arg_opt_str(args, "fill"),
                align,
            };
            let fonts = golden_font_book();
            let (result, _) = text::add_text_box(svg, "el-tb", &input, &fonts)
                .unwrap_or_else(|err| panic!("{}: {:?}", case.label, err.message()));
            CaseOutcome::Text(result)
        }
        "textbox width" => {
            let element_id = arg_str(args, "elementId");
            let width = arg_f64(args, "width");
            let fonts = golden_font_book();
            let (result, _) = text::resize_text_box(svg, element_id, width, &fonts, false)
                .unwrap_or_else(|err| panic!("{}: {:?}", case.label, err.message()));
            CaseOutcome::Text(result)
        }
        "textbox align" => {
            let element_id = arg_str(args, "elementId");
            let align = parse_text_align(arg_str(args, "align"));
            let fonts = golden_font_book();
            let (result, _) = text::realign_text_box(svg, element_id, align, &fonts, false)
                .unwrap_or_else(|err| panic!("{}: {:?}", case.label, err.message()));
            CaseOutcome::Text(result)
        }
        "element copy" => {
            let ids = arg_str_vec(args, "elementIds");
            let payload = clipboard::extract_elements_for_copy(svg, GOLDEN_SLIDE_PATH, &ids)
                .unwrap_or_else(|err| panic!("{}: {:?}", case.label, err.message()));
            CaseOutcome::Text(
                payload
                    .elements
                    .first()
                    .expect("copy payload must contain at least one element")
                    .clone(),
            )
        }
        "element paste" => {
            let dx = arg_f64(args, "dx");
            let dy = arg_f64(args, "dy");
            let payload = ClipboardPayload {
                source_slide_path: GOLDEN_SLIDE_PATH.to_string(),
                elements: vec![
                    r##"<g id="el-old"><rect x="0" y="0" width="1" height="1"/></g>"##.to_string(),
                ],
                effects: Vec::new(),
                view_box: None,
            };
            let mut n = 0u32;
            let result =
                clipboard::paste_elements(svg, GOLDEN_SLIDE_PATH, &payload, dx, dy, || {
                    n += 1;
                    format!("el-generated-{n}")
                })
                .unwrap_or_else(|err| panic!("{}: {:?}", case.label, err.message()));
            CaseOutcome::Text(result.updated)
        }
        "element duplicate" => {
            let ids = arg_str_vec(args, "elementIds");
            let dx = arg_f64(args, "dx");
            let dy = arg_f64(args, "dy");
            let payload = clipboard::extract_elements_for_copy(svg, GOLDEN_SLIDE_PATH, &ids)
                .unwrap_or_else(|err| panic!("{}: {:?}", case.label, err.message()));
            let mut n = 0u32;
            let result =
                clipboard::paste_elements(svg, GOLDEN_SLIDE_PATH, &payload, dx, dy, || {
                    n += 1;
                    format!("el-dup-{n}")
                })
                .unwrap_or_else(|err| panic!("{}: {:?}", case.label, err.message()));
            CaseOutcome::Text(result.updated)
        }
        "comment add" => {
            let comment = comment_from_json(&args["comment"]);
            let result = comments::add_slide_comment(svg, &comment)
                .unwrap_or_else(|err| panic!("{}: {:?}", case.label, err.message()));
            CaseOutcome::Text(result)
        }
        "comment edit" => {
            let comment_id = arg_str(args, "commentId");
            let text_value = arg_str(args, "text");
            let result = comments::edit_slide_comment(svg, comment_id, text_value)
                .unwrap_or_else(|err| panic!("{}: {:?}", case.label, err.message()));
            CaseOutcome::Text(result)
        }
        "comment delete" => {
            let comment_id = arg_str(args, "commentId");
            let result = comments::delete_slide_comment(svg, comment_id)
                .unwrap_or_else(|err| panic!("{}: {:?}", case.label, err.message()));
            CaseOutcome::Text(result)
        }
        "comment list" => {
            let result = comments::read_slide_comments(svg)
                .unwrap_or_else(|err| panic!("{}: {:?}", case.label, err.message()));
            CaseOutcome::Comments(result)
        }
        other => panic!(
            "no dispatch wired up for golden command {other:?} (label {:?})",
            case.label
        ),
    }
}

#[test]
fn element_commands_match_ts_reference_for_every_command() {
    let raw = fs::read_to_string(golden_path("element_commands.json")).expect(
        "tests/golden/element_commands.json must exist — run `node scripts/gen-golden.mjs`",
    );
    let cases: Vec<ElementCommandCase> =
        serde_json::from_str(&raw).expect("golden file must be valid JSON");

    let commands_covered: std::collections::HashSet<&str> =
        cases.iter().map(|c| c.command.as_str()).collect();
    assert_eq!(
        commands_covered.len(),
        29,
        "NOOP-309 requires golden coverage for exactly 29 commands, found {}: {:?}",
        commands_covered.len(),
        commands_covered
    );

    let mut failures = Vec::new();
    for case in &cases {
        match run_element_command_case(case) {
            CaseOutcome::Text(actual) => {
                let expected = case.expected.as_str().unwrap_or_else(|| {
                    panic!("{}: golden `expected` must be a string", case.label)
                });
                if actual != expected {
                    failures.push(format!(
                        "{} / {}: mismatch\n  expected={:?}\n  actual={:?}",
                        case.command, case.label, expected, actual
                    ));
                }
            }
            CaseOutcome::Comments(actual) => {
                let expected = case.expected.as_array().unwrap_or_else(|| {
                    panic!("{}: golden `expected` must be an array", case.label)
                });
                if actual.len() != expected.len() {
                    failures.push(format!(
                        "{} / {}: comment count mismatch: expected {} actual {}",
                        case.command,
                        case.label,
                        expected.len(),
                        actual.len()
                    ));
                    continue;
                }
                for (i, (a, e)) in actual.iter().zip(expected.iter()).enumerate() {
                    let expected_comment = comment_from_json(e);
                    if *a != expected_comment {
                        failures.push(format!(
                            "{} / {} [{}]: mismatch\n  expected={:?}\n  actual={:?}",
                            case.command, case.label, i, expected_comment, a
                        ));
                    }
                }
            }
        }
    }
    assert!(
        failures.is_empty(),
        "element-command golden mismatches against TS reference:\n{}",
        failures.join("\n")
    );
}
