//! Golden-fixture tests for the crate's pure-function public API — the
//! second of the three public boundaries this ticket tests at (plan section
//! 6.2): `co-motion` the library's exported functions, fed fixtures whose
//! expected values were generated by actually running the real TypeScript
//! implementation (`scripts/gen-golden.mjs`), never by hand-computing or
//! capturing this Rust port's own output.
//!
//! Regenerate fixtures with `node scripts/gen-golden.mjs` after building
//! `packages/core` (`npm run build --workspace=packages/core`); this test
//! file only reads `tests/golden/*.json`, it never regenerates them
//! (network/`packages/core` build tooling aren't guaranteed available
//! wherever `cargo test` runs).

use co_motion::geometry::bbox::{
    ElementBoundsOptions, TextBoundsContext, element_bounds, format_bbox, path_bounds,
    primitive_bounds,
};
use co_motion::geometry::transform::IDENTITY;
use co_motion::media_format::{MediaKind, detect_media_format};
use co_motion::slide::format::{SlideElement, SlideElementKind, SlidePrimitive, TextAlign};
use co_motion::slide::scan::{ScannedNode, scan_document};
use co_motion::slide::table_grid::TableGrid;
use co_motion::svgnum::format_svg_number;
use co_motion::text::font::{DEFAULT_FONT_BYTES, FontMetrics, parse_font};
use co_motion::text::metrics::measure_text_width;
use co_motion::text::render::render_text_box_content;
use co_motion::text::wrap::{Align, WrapOptions, wrap_text};
use serde::Deserialize;
use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;

fn golden_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/golden")
        .join(name)
}

#[derive(Deserialize)]
struct SvgNumberCase {
    input: f64,
    expected: String,
}

#[test]
fn svgnum_matches_ts_reference_for_every_golden_case() {
    let raw = fs::read_to_string(golden_path("svgnum.json"))
        .expect("tests/golden/svgnum.json must exist — run `node scripts/gen-golden.mjs`");
    let cases: Vec<SvgNumberCase> =
        serde_json::from_str(&raw).expect("golden file must be valid JSON");
    assert!(
        cases.len() >= 200,
        "plan AC9 requires >= 200 svgnum golden cases, found {}",
        cases.len()
    );

    let mut failures = Vec::new();
    for case in &cases {
        let actual = format_svg_number(case.input);
        if actual != case.expected {
            failures.push(format!(
                "input={} expected={:?} actual={:?}",
                case.input, case.expected, actual
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "svgnum mismatches against TS golden data:\n{}",
        failures.join("\n")
    );
}

#[derive(Deserialize)]
struct TextWrapFixtureInput {
    text: String,
    width: f64,
    #[serde(rename = "fontSizePx")]
    font_size_px: f64,
}

#[derive(Deserialize)]
struct TextWrapFixture {
    input: TextWrapFixtureInput,
    #[serde(rename = "expectedInnerMarkup")]
    expected_inner_markup: String,
    #[serde(rename = "expectedTextHeight")]
    expected_text_height: String,
}

/// The exact fixture from the implementation plan (NOOP-277 section 5, AC9):
/// a two-paragraph CJK+ASCII string wrapped at width 300 / font-size 24,
/// run end-to-end through the real CLI (`co-motion textbox add`) and
/// captured by `scripts/gen-golden.mjs`. This is the single most
/// load-bearing golden case in this ticket — it exercises wrap.rs, render.rs,
/// runs.rs (empty-runs path), font.rs (real embedded TTF: cmap/hmtx/GSUB),
/// and svgnum.rs together, matching how they're actually used in
/// combination rather than only in isolation.
#[test]
fn text_wrap_and_render_matches_ts_reference_fixture() {
    let raw = fs::read_to_string(golden_path("text_wrap_fixture.json")).expect(
        "tests/golden/text_wrap_fixture.json must exist — run `node scripts/gen-golden.mjs`",
    );
    let fixture: TextWrapFixture =
        serde_json::from_str(&raw).expect("golden file must be valid JSON");

    let font = parse_font(DEFAULT_FONT_BYTES).expect("embedded default font must parse");
    let options = WrapOptions {
        width: fixture.input.width,
        font: &font,
        font_size_px: fixture.input.font_size_px,
        align: Align::Left,
        indents: None,
    };

    let wrapped =
        wrap_text(&fixture.input.text, &options).expect("fixture text must wrap without error");
    let markup = render_text_box_content(&wrapped.lines, &[]);
    let height = format_svg_number(wrapped.height);

    assert_eq!(
        markup, fixture.expected_inner_markup,
        "rendered <tspan> markup diverges from the TS-generated golden fixture"
    );
    assert_eq!(
        height, fixture.expected_text_height,
        "text-box height diverges from the TS-generated golden fixture"
    );
}

// --- scan.json --------------------------------------------------------
//
// NOOP-292 (Review round 1, NOOP-283, FAIL item 1): scan.rs had no golden
// coverage at all — its 18 hand-written tests were self-verified by the
// same porting pass that wrote the code under test. These cases run the
// real `scanDocument` (`scripts/gen-golden.mjs`'s `genScan`), covering the
// module's four rules plus one case per distinct error message.

#[derive(Deserialize)]
struct ScanAttributeCase {
    name: String,
    value: String,
    start: usize,
    end: usize,
}

#[derive(Deserialize)]
struct ScanNodeCase {
    tag: String,
    attributes: Vec<ScanAttributeCase>,
    start: usize,
    end: usize,
    #[serde(rename = "contentStart")]
    content_start: usize,
    #[serde(rename = "contentEnd")]
    content_end: usize,
    #[serde(rename = "selfClosing")]
    self_closing: bool,
    children: Vec<ScanNodeCase>,
}

#[derive(Deserialize)]
struct ScanTreeCase {
    label: String,
    svg: String,
    expected: Vec<ScanNodeCase>,
}

#[derive(Deserialize)]
struct ScanErrorCase {
    label: String,
    svg: String,
    #[serde(rename = "expectedMessage")]
    expected_message: String,
}

#[derive(Deserialize)]
struct ScanGolden {
    tree: Vec<ScanTreeCase>,
    errors: Vec<ScanErrorCase>,
}

fn assert_scan_node_matches(actual: &ScannedNode, expected: &ScanNodeCase, path: &str) {
    assert_eq!(actual.tag, expected.tag, "{path}: tag mismatch");
    assert_eq!(actual.start, expected.start, "{path}: start mismatch");
    assert_eq!(actual.end, expected.end, "{path}: end mismatch");
    assert_eq!(
        actual.content_start, expected.content_start,
        "{path}: contentStart mismatch"
    );
    assert_eq!(
        actual.content_end, expected.content_end,
        "{path}: contentEnd mismatch"
    );
    assert_eq!(
        actual.self_closing, expected.self_closing,
        "{path}: selfClosing mismatch"
    );
    assert_eq!(
        actual.attributes.len(),
        expected.attributes.len(),
        "{path}: attribute count mismatch"
    );
    for (i, (a, e)) in actual
        .attributes
        .iter()
        .zip(expected.attributes.iter())
        .enumerate()
    {
        assert_eq!(a.name, e.name, "{path}: attribute[{i}].name mismatch");
        assert_eq!(a.value, e.value, "{path}: attribute[{i}].value mismatch");
        assert_eq!(a.start, e.start, "{path}: attribute[{i}].start mismatch");
        assert_eq!(a.end, e.end, "{path}: attribute[{i}].end mismatch");
    }
    assert_eq!(
        actual.children.len(),
        expected.children.len(),
        "{path}: children count mismatch"
    );
    for (i, (a, e)) in actual
        .children
        .iter()
        .zip(expected.children.iter())
        .enumerate()
    {
        assert_scan_node_matches(a, e, &format!("{path}/children[{i}]"));
    }
}

#[test]
fn scan_document_matches_ts_reference_tree_and_error_cases() {
    let raw = fs::read_to_string(golden_path("scan.json"))
        .expect("tests/golden/scan.json must exist — run `node scripts/gen-golden.mjs`");
    let golden: ScanGolden = serde_json::from_str(&raw).expect("golden file must be valid JSON");

    for case in &golden.tree {
        let actual = scan_document(&case.svg).unwrap_or_else(|err| {
            panic!(
                "case {:?}: expected scan_document to succeed, got {:?}",
                case.label,
                err.message()
            )
        });
        assert_eq!(
            actual.len(),
            case.expected.len(),
            "case {:?}: top-level node count mismatch",
            case.label
        );
        for (i, (a, e)) in actual.iter().zip(case.expected.iter()).enumerate() {
            assert_scan_node_matches(a, e, &format!("case {:?} [{}]", case.label, i));
        }
    }

    for case in &golden.errors {
        let err = scan_document(&case.svg).expect_err(&format!(
            "case {:?}: expected scan_document to fail",
            case.label
        ));
        assert_eq!(
            err.message(),
            case.expected_message,
            "case {:?}: error message mismatch",
            case.label
        );
    }
}

// --- bbox.json ----------------------------------------------------------
//
// NOOP-292 (Review round 1, NOOP-283, FAIL item 1): one golden case per
// primitive/element kind plan A9 requires — rect/ellipse/line/path
// (including the elliptical-arc rejection)/group/table/text — each
// compared as its four `format_svg_number` fields, run through the real
// `primitiveBounds`/`elementBounds`/`pathBounds` (`scripts/gen-golden.mjs`'s
// `genBbox`).

#[derive(Deserialize)]
struct FormattedRectCase {
    x: String,
    y: String,
    width: String,
    height: String,
}

#[derive(Deserialize)]
struct BboxPrimitiveCase {
    label: String,
    tag: String,
    attrs: HashMap<String, String>,
    expected: FormattedRectCase,
}

#[derive(Deserialize)]
struct BboxPathOkCase {
    label: String,
    d: String,
    expected: FormattedRectCase,
}

#[derive(Deserialize)]
struct BboxPathArcCase {
    label: String,
    d: String,
    #[serde(rename = "expectedError")]
    expected_error: String,
}

#[derive(Deserialize)]
struct BboxPathCases {
    ok: BboxPathOkCase,
    #[serde(rename = "arcRejected")]
    arc_rejected: BboxPathArcCase,
}

#[derive(Deserialize)]
struct BboxGroupCase {
    label: String,
    expected: FormattedRectCase,
}

#[derive(Deserialize)]
struct BboxTableCase {
    label: String,
    cols: Vec<f64>,
    rows: Vec<f64>,
    expected: FormattedRectCase,
}

#[derive(Deserialize)]
struct BboxTextCase {
    label: String,
    attrs: HashMap<String, String>,
    text: String,
    expected: FormattedRectCase,
}

#[derive(Deserialize)]
struct BboxGolden {
    primitives: Vec<BboxPrimitiveCase>,
    path: BboxPathCases,
    group: BboxGroupCase,
    table: BboxTableCase,
    text: BboxTextCase,
}

fn primitive_from_attrs(tag: &str, attrs: &HashMap<String, String>) -> SlidePrimitive {
    SlidePrimitive {
        tag: tag.to_string(),
        attrs: attrs.iter().map(|(k, v)| (k.clone(), v.clone())).collect(),
        text: String::new(),
        tspan_count: 0,
        runs: Vec::new(),
    }
}

fn bbox_leaf_element(
    id: &str,
    kind: SlideElementKind,
    primitives: Vec<SlidePrimitive>,
) -> SlideElement {
    SlideElement {
        id: id.to_string(),
        name: None,
        media: None,
        kind,
        transform: None,
        matrix: IDENTITY,
        children: Vec::new(),
        primitives,
        text_width: None,
        text_height: None,
        text_align: TextAlign::Left,
        table: None,
    }
}

fn assert_formatted_rect_eq(
    actual: &co_motion::geometry::bbox::FormattedBbox,
    expected: &FormattedRectCase,
    label: &str,
) {
    assert_eq!(actual.x, expected.x, "{label}: x mismatch");
    assert_eq!(actual.y, expected.y, "{label}: y mismatch");
    assert_eq!(actual.width, expected.width, "{label}: width mismatch");
    assert_eq!(actual.height, expected.height, "{label}: height mismatch");
}

#[test]
fn bbox_matches_ts_reference_for_every_primitive_and_element_kind() {
    let raw = fs::read_to_string(golden_path("bbox.json"))
        .expect("tests/golden/bbox.json must exist — run `node scripts/gen-golden.mjs`");
    let golden: BboxGolden = serde_json::from_str(&raw).expect("golden file must be valid JSON");

    for case in &golden.primitives {
        let primitive = primitive_from_attrs(&case.tag, &case.attrs);
        let bbox = primitive_bounds(&primitive, None)
            .unwrap_or_else(|err| panic!("case {:?}: {:?}", case.label, err.message()));
        assert_formatted_rect_eq(&format_bbox(&bbox), &case.expected, &case.label);
    }

    let ok_bbox = path_bounds(&golden.path.ok.d).expect("path-cubic-bezier case must succeed");
    assert_formatted_rect_eq(
        &format_bbox(&ok_bbox),
        &golden.path.ok.expected,
        &golden.path.ok.label,
    );

    let arc_err = path_bounds(&golden.path.arc_rejected.d).expect_err("arc path must be rejected");
    assert_eq!(
        arc_err.message(),
        golden.path.arc_rejected.expected_error,
        "case {:?}: arc rejection message mismatch",
        golden.path.arc_rejected.label
    );

    // group: union of two children's transformed boxes.
    let child_a = bbox_leaf_element(
        "child-a",
        SlideElementKind::Rect,
        vec![primitive_from_attrs(
            "rect",
            &HashMap::from([
                ("x".to_string(), "2".to_string()),
                ("y".to_string(), "3".to_string()),
                ("width".to_string(), "8".to_string()),
                ("height".to_string(), "6".to_string()),
            ]),
        )],
    );
    let child_b = bbox_leaf_element(
        "child-b",
        SlideElementKind::Ellipse,
        vec![primitive_from_attrs(
            "ellipse",
            &HashMap::from([
                ("cx".to_string(), "30".to_string()),
                ("cy".to_string(), "10".to_string()),
                ("rx".to_string(), "4".to_string()),
                ("ry".to_string(), "2".to_string()),
            ]),
        )],
    );
    let mut group = bbox_leaf_element("group-1", SlideElementKind::Group, Vec::new());
    group.children = vec![child_a, child_b];
    let options = ElementBoundsOptions {
        ancestors: &[],
        fonts: None,
    };
    let group_bbox = element_bounds(&group, &options).expect("group bbox must succeed");
    assert_formatted_rect_eq(
        &format_bbox(&group_bbox),
        &golden.group.expected,
        &golden.group.label,
    );

    // table: declared grid extent, not a primitive union.
    let mut table_element = bbox_leaf_element("table-1", SlideElementKind::Table, Vec::new());
    table_element.table = Some(TableGrid {
        cols: golden.table.cols.clone(),
        rows: golden.table.rows.clone(),
    });
    let table_bbox = element_bounds(&table_element, &options).expect("table bbox must succeed");
    assert_formatted_rect_eq(
        &format_bbox(&table_bbox),
        &golden.table.expected,
        &golden.table.label,
    );

    // text: a plain `<text>` (no tspans), measured via the real embedded
    // default font — the same physical .ttf `packages/core/dist`'s
    // `parseFont` read to produce this golden fixture.
    let font = parse_font(DEFAULT_FONT_BYTES).expect("embedded default font must parse");
    let fonts: HashMap<String, Box<dyn FontMetrics>> = HashMap::from([(
        "Noto Sans TC".to_string(),
        Box::new(font) as Box<dyn FontMetrics>,
    )]);
    let text_primitive = SlidePrimitive {
        text: golden.text.text.clone(),
        ..primitive_from_attrs("text", &golden.text.attrs)
    };
    let text_context = TextBoundsContext {
        fonts: &fonts,
        text_width: None,
        text_height: None,
        element_id: "text-1".to_string(),
    };
    let text_bbox =
        primitive_bounds(&text_primitive, Some(&text_context)).expect("text bbox must succeed");
    assert_formatted_rect_eq(
        &format_bbox(&text_bbox),
        &golden.text.expected,
        &golden.text.label,
    );
}

// --- font.json ------------------------------------------------------------
//
// NOOP-292 (Review round 1, NOOP-283, FAIL item 1): `parseFont`'s line
// metrics plus >= 50 `measureTextWidth` golden cases, run against the real
// bundled font (`scripts/gen-golden.mjs`'s `genFont`) — font.rs and
// metrics.rs had no golden coverage at all before this.

#[derive(Deserialize)]
struct FontMetricsCase {
    #[serde(rename = "unitsPerEm")]
    units_per_em: u16,
    ascender: i16,
    descender: i16,
    #[serde(rename = "lineGap")]
    line_gap: i16,
}

#[derive(Deserialize)]
struct MeasureTextWidthCase {
    text: String,
    #[serde(rename = "fontSizePx")]
    font_size_px: f64,
    expected: String,
}

#[derive(Deserialize)]
struct FontGolden {
    metrics: FontMetricsCase,
    #[serde(rename = "measureTextWidth")]
    measure_text_width: Vec<MeasureTextWidthCase>,
}

#[test]
fn font_metrics_and_measure_text_width_match_ts_reference() {
    let raw = fs::read_to_string(golden_path("font.json"))
        .expect("tests/golden/font.json must exist — run `node scripts/gen-golden.mjs`");
    let golden: FontGolden = serde_json::from_str(&raw).expect("golden file must be valid JSON");
    assert!(
        golden.measure_text_width.len() >= 50,
        "plan A9 requires >= 50 measureTextWidth golden cases, found {}",
        golden.measure_text_width.len()
    );

    let font = parse_font(DEFAULT_FONT_BYTES).expect("embedded default font must parse");
    assert_eq!(
        font.units_per_em(),
        golden.metrics.units_per_em,
        "unitsPerEm mismatch"
    );
    assert_eq!(
        font.ascender(),
        golden.metrics.ascender,
        "ascender mismatch"
    );
    assert_eq!(
        font.descender(),
        golden.metrics.descender,
        "descender mismatch"
    );
    assert_eq!(font.line_gap(), golden.metrics.line_gap, "lineGap mismatch");

    let mut failures = Vec::new();
    for case in &golden.measure_text_width {
        let actual = measure_text_width(&font, &case.text, case.font_size_px)
            .unwrap_or_else(|err| panic!("text={:?}: {:?}", case.text, err.message()));
        let formatted = format_svg_number(actual);
        if formatted != case.expected {
            failures.push(format!(
                "text={:?} fontSizePx={} expected={:?} actual={:?}",
                case.text, case.font_size_px, case.expected, formatted
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "measureTextWidth mismatches against TS golden data:\n{}",
        failures.join("\n")
    );
}

// --- text_wrap_extra_cases.json --------------------------------------------
//
// NOOP-292 (Review round 1, NOOP-283, FAIL item 1): the plan's single
// `text_wrap_fixture` (full CLI round trip) doesn't cover CJK-only,
// ASCII-only, an explicit hard break, list-paragraph indents, a single word
// wider than the box, or an empty paragraph. These six run
// `wrapText`/`renderTextBoxContent` directly against the real bundled font
// (`scripts/gen-golden.mjs`'s `genTextWrapExtraCases`).

#[derive(Deserialize)]
struct TextWrapExtraInput {
    text: String,
    width: f64,
    #[serde(rename = "fontSizePx")]
    font_size_px: f64,
    #[serde(default)]
    indents: Option<Vec<f64>>,
}

#[derive(Deserialize)]
struct TextWrapExtraCase {
    label: String,
    input: TextWrapExtraInput,
    #[serde(rename = "expectedInnerMarkup")]
    expected_inner_markup: String,
    #[serde(rename = "expectedTextHeight")]
    expected_text_height: String,
}

#[test]
fn text_wrap_extra_cases_match_ts_reference() {
    let raw = fs::read_to_string(golden_path("text_wrap_extra_cases.json")).expect(
        "tests/golden/text_wrap_extra_cases.json must exist — run `node scripts/gen-golden.mjs`",
    );
    let cases: Vec<TextWrapExtraCase> =
        serde_json::from_str(&raw).expect("golden file must be valid JSON");
    assert!(
        cases.len() >= 6,
        "plan NOOP-292 requires >= 6 supplementary text-wrap golden cases, found {}",
        cases.len()
    );

    let font = parse_font(DEFAULT_FONT_BYTES).expect("embedded default font must parse");
    let mut failures = Vec::new();
    for case in &cases {
        let options = WrapOptions {
            width: case.input.width,
            font: &font,
            font_size_px: case.input.font_size_px,
            align: Align::Left,
            indents: case.input.indents.as_deref(),
        };
        let wrapped = wrap_text(&case.input.text, &options)
            .unwrap_or_else(|err| panic!("case {:?}: {:?}", case.label, err.message()));
        let markup = render_text_box_content(&wrapped.lines, &[]);
        let height = format_svg_number(wrapped.height);
        if markup != case.expected_inner_markup || height != case.expected_text_height {
            failures.push(format!(
                "case={:?}\n  expected_markup={:?}\n  actual_markup={:?}\n  expected_height={:?}\n  actual_height={:?}",
                case.label, case.expected_inner_markup, markup, case.expected_text_height, height
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "text-wrap extra-case mismatches against TS golden data:\n{}",
        failures.join("\n")
    );
}

#[derive(Deserialize)]
struct MediaFormatExpected {
    #[serde(rename = "mimeType")]
    mime_type: String,
    kind: String,
    #[serde(rename = "aliasExtensions")]
    alias_extensions: Vec<String>,
    extension: String,
}

#[derive(Deserialize)]
struct MediaFormatCase {
    label: String,
    bytes: Vec<u8>,
    expected: Option<MediaFormatExpected>,
}

/// Acceptance criterion A9: `detect_media_format` against every golden
/// case's REAL `detectMediaFormat` (TS) output, not this port's own
/// reasoning about what the TS behavior should be — the fixture generator
/// imports and calls the actual `packages/core/dist/media-format.js`.
#[test]
fn media_format_matches_ts_reference_for_every_golden_case() {
    let raw = fs::read_to_string(golden_path("media_format.json"))
        .expect("tests/golden/media_format.json must exist — run `node scripts/gen-golden.mjs`");
    let cases: Vec<MediaFormatCase> =
        serde_json::from_str(&raw).expect("golden file must be valid JSON");
    assert!(
        cases.len() >= 15,
        "expected at least one golden case per recognised format, found {}",
        cases.len()
    );

    let mut failures = Vec::new();
    for case in &cases {
        let actual = detect_media_format(&case.bytes);
        match (&case.expected, actual) {
            (None, None) => {}
            (Some(expected), Some(actual)) => {
                let kind_str = match actual.kind {
                    MediaKind::Image => "image",
                    MediaKind::Video => "video",
                    MediaKind::Audio => "audio",
                };
                let alias: Vec<String> = actual
                    .alias_extensions
                    .iter()
                    .map(|s| s.to_string())
                    .collect();
                if expected.extension != actual.extension
                    || expected.mime_type != actual.mime_type
                    || expected.kind != kind_str
                    || expected.alias_extensions != alias
                {
                    failures.push(format!(
                        "case={:?}: expected {}/{}/{}/{:?}, got {}/{}/{}/{:?}",
                        case.label,
                        expected.extension,
                        expected.mime_type,
                        expected.kind,
                        expected.alias_extensions,
                        actual.extension,
                        actual.mime_type,
                        kind_str,
                        alias
                    ));
                }
            }
            (expected, actual) => {
                failures.push(format!(
                    "case={:?}: expected {:?}, got {:?}",
                    case.label,
                    expected.is_some(),
                    actual.is_some()
                ));
            }
        }
    }
    assert!(
        failures.is_empty(),
        "media_format mismatches against TS golden data:\n{}",
        failures.join("\n")
    );
}
