//! Golden-fixture tests for the crate's pure-function public API — the
//! second of the three public boundaries this ticket tests at (plan section
//! 6.2): `co-motion` the library's exported functions, fed fixtures whose
//! expected values were generated by actually running the real TypeScript
//! implementation (`scripts/gen-golden.mjs`), never by hand-computing or
//! capturing this Rust port's own output.
//!
//! Regenerate fixtures with `node scripts/gen-golden.mjs` after building
//! `packages/core` (`npm run build --workspace=packages/core`); this test
//! file only reads `tests/golden/*.json`, it never regenerates them
//! (network/`packages/core` build tooling aren't guaranteed available
//! wherever `cargo test` runs).

use co_motion::svgnum::format_svg_number;
use co_motion::text::font::{parse_font, DEFAULT_FONT_BYTES};
use co_motion::text::render::render_text_box_content;
use co_motion::text::wrap::{wrap_text, Align, WrapOptions};
use serde::Deserialize;
use std::fs;
use std::path::PathBuf;

fn golden_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/golden").join(name)
}

#[derive(Deserialize)]
struct SvgNumberCase {
    input: f64,
    expected: String,
}

#[test]
fn svgnum_matches_ts_reference_for_every_golden_case() {
    let raw = fs::read_to_string(golden_path("svgnum.json"))
        .expect("tests/golden/svgnum.json must exist — run `node scripts/gen-golden.mjs`");
    let cases: Vec<SvgNumberCase> = serde_json::from_str(&raw).expect("golden file must be valid JSON");
    assert!(cases.len() >= 200, "plan AC9 requires >= 200 svgnum golden cases, found {}", cases.len());

    let mut failures = Vec::new();
    for case in &cases {
        let actual = format_svg_number(case.input);
        if actual != case.expected {
            failures.push(format!("input={} expected={:?} actual={:?}", case.input, case.expected, actual));
        }
    }
    assert!(failures.is_empty(), "svgnum mismatches against TS golden data:\n{}", failures.join("\n"));
}

#[derive(Deserialize)]
struct TextWrapFixtureInput {
    text: String,
    width: f64,
    #[serde(rename = "fontSizePx")]
    font_size_px: f64,
}

#[derive(Deserialize)]
struct TextWrapFixture {
    input: TextWrapFixtureInput,
    #[serde(rename = "expectedInnerMarkup")]
    expected_inner_markup: String,
    #[serde(rename = "expectedTextHeight")]
    expected_text_height: String,
}

/// The exact fixture from the implementation plan (NOOP-277 section 5, AC9):
/// a two-paragraph CJK+ASCII string wrapped at width 300 / font-size 24,
/// run end-to-end through the real CLI (`co-motion textbox add`) and
/// captured by `scripts/gen-golden.mjs`. This is the single most
/// load-bearing golden case in this ticket — it exercises wrap.rs, render.rs,
/// runs.rs (empty-runs path), font.rs (real embedded TTF: cmap/hmtx/GSUB),
/// and svgnum.rs together, matching how they're actually used in
/// combination rather than only in isolation.
#[test]
fn text_wrap_and_render_matches_ts_reference_fixture() {
    let raw = fs::read_to_string(golden_path("text_wrap_fixture.json"))
        .expect("tests/golden/text_wrap_fixture.json must exist — run `node scripts/gen-golden.mjs`");
    let fixture: TextWrapFixture = serde_json::from_str(&raw).expect("golden file must be valid JSON");

    let font = parse_font(DEFAULT_FONT_BYTES).expect("embedded default font must parse");
    let options = WrapOptions { width: fixture.input.width, font: &font, font_size_px: fixture.input.font_size_px, align: Align::Left, indents: None };

    let wrapped = wrap_text(&fixture.input.text, &options).expect("fixture text must wrap without error");
    let markup = render_text_box_content(&wrapped.lines, &[]);
    let height = format_svg_number(wrapped.height);

    assert_eq!(markup, fixture.expected_inner_markup, "rendered <tspan> markup diverges from the TS-generated golden fixture");
    assert_eq!(height, fixture.expected_text_height, "text-box height diverges from the TS-generated golden fixture");
}
