//! Golden-fixture tests for the crate's pure-function public API — the
//! second of the three public boundaries this ticket tests at (plan section
//! 6.2): `co-motion` the library's exported functions, fed fixtures whose
//! expected values were generated by actually running the real TypeScript
//! implementation (`scripts/gen-golden.mjs`), never by hand-computing or
//! capturing this Rust port's own output.
//!
//! Regenerate fixtures with `node scripts/gen-golden.mjs` after building
//! `packages/core` (`npm run build --workspace=packages/core`); this test
//! file only reads `tests/golden/*.json`, it never regenerates them
//! (network/`packages/core` build tooling aren't guaranteed available
//! wherever `cargo test` runs).

use co_motion::container::{pack_directory, unpack_container};
use co_motion::geometry::bbox::{
    ElementBoundsOptions, TextBoundsContext, element_bounds, format_bbox, path_bounds,
    primitive_bounds,
};
use co_motion::geometry::transform::IDENTITY;
use co_motion::slide::format::{SlideElement, SlideElementKind, SlidePrimitive, TextAlign};
use co_motion::slide::scan::{ScannedNode, scan_document};
use co_motion::slide::table_grid::TableGrid;
use co_motion::svgnum::format_svg_number;
use co_motion::text::font::{DEFAULT_FONT_BYTES, FontMetrics, parse_font};
use co_motion::text::metrics::measure_text_width;
use co_motion::text::render::render_text_box_content;
use co_motion::text::wrap::{Align, WrapOptions, wrap_text};
use co_motion::workspace::migrate::migrate_to_v4;
use serde::Deserialize;
use std::collections::{BTreeMap, HashMap};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn golden_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/golden")
        .join(name)
}

#[derive(Deserialize)]
struct SvgNumberCase {
    input: f64,
    expected: String,
}

#[test]
fn svgnum_matches_ts_reference_for_every_golden_case() {
    let raw = fs::read_to_string(golden_path("svgnum.json"))
        .expect("tests/golden/svgnum.json must exist — run `node scripts/gen-golden.mjs`");
    let cases: Vec<SvgNumberCase> =
        serde_json::from_str(&raw).expect("golden file must be valid JSON");
    assert!(
        cases.len() >= 200,
        "plan AC9 requires >= 200 svgnum golden cases, found {}",
        cases.len()
    );

    let mut failures = Vec::new();
    for case in &cases {
        let actual = format_svg_number(case.input);
        if actual != case.expected {
            failures.push(format!(
                "input={} expected={:?} actual={:?}",
                case.input, case.expected, actual
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "svgnum mismatches against TS golden data:\n{}",
        failures.join("\n")
    );
}

#[derive(Deserialize)]
struct TextWrapFixtureInput {
    text: String,
    width: f64,
    #[serde(rename = "fontSizePx")]
    font_size_px: f64,
}

#[derive(Deserialize)]
struct TextWrapFixture {
    input: TextWrapFixtureInput,
    #[serde(rename = "expectedInnerMarkup")]
    expected_inner_markup: String,
    #[serde(rename = "expectedTextHeight")]
    expected_text_height: String,
}

/// The exact fixture from the implementation plan (NOOP-277 section 5, AC9):
/// a two-paragraph CJK+ASCII string wrapped at width 300 / font-size 24,
/// run end-to-end through the real CLI (`co-motion textbox add`) and
/// captured by `scripts/gen-golden.mjs`. This is the single most
/// load-bearing golden case in this ticket — it exercises wrap.rs, render.rs,
/// runs.rs (empty-runs path), font.rs (real embedded TTF: cmap/hmtx/GSUB),
/// and svgnum.rs together, matching how they're actually used in
/// combination rather than only in isolation.
#[test]
fn text_wrap_and_render_matches_ts_reference_fixture() {
    let raw = fs::read_to_string(golden_path("text_wrap_fixture.json")).expect(
        "tests/golden/text_wrap_fixture.json must exist — run `node scripts/gen-golden.mjs`",
    );
    let fixture: TextWrapFixture =
        serde_json::from_str(&raw).expect("golden file must be valid JSON");

    let font = parse_font(DEFAULT_FONT_BYTES).expect("embedded default font must parse");
    let options = WrapOptions {
        width: fixture.input.width,
        font: &font,
        font_size_px: fixture.input.font_size_px,
        align: Align::Left,
        indents: None,
    };

    let wrapped =
        wrap_text(&fixture.input.text, &options).expect("fixture text must wrap without error");
    let markup = render_text_box_content(&wrapped.lines, &[]);
    let height = format_svg_number(wrapped.height);

    assert_eq!(
        markup, fixture.expected_inner_markup,
        "rendered <tspan> markup diverges from the TS-generated golden fixture"
    );
    assert_eq!(
        height, fixture.expected_text_height,
        "text-box height diverges from the TS-generated golden fixture"
    );
}

// --- scan.json --------------------------------------------------------
//
// NOOP-292 (Review round 1, NOOP-283, FAIL item 1): scan.rs had no golden
// coverage at all — its 18 hand-written tests were self-verified by the
// same porting pass that wrote the code under test. These cases run the
// real `scanDocument` (`scripts/gen-golden.mjs`'s `genScan`), covering the
// module's four rules plus one case per distinct error message.

#[derive(Deserialize)]
struct ScanAttributeCase {
    name: String,
    value: String,
    start: usize,
    end: usize,
}

#[derive(Deserialize)]
struct ScanNodeCase {
    tag: String,
    attributes: Vec<ScanAttributeCase>,
    start: usize,
    end: usize,
    #[serde(rename = "contentStart")]
    content_start: usize,
    #[serde(rename = "contentEnd")]
    content_end: usize,
    #[serde(rename = "selfClosing")]
    self_closing: bool,
    children: Vec<ScanNodeCase>,
}

#[derive(Deserialize)]
struct ScanTreeCase {
    label: String,
    svg: String,
    expected: Vec<ScanNodeCase>,
}

#[derive(Deserialize)]
struct ScanErrorCase {
    label: String,
    svg: String,
    #[serde(rename = "expectedMessage")]
    expected_message: String,
}

#[derive(Deserialize)]
struct ScanGolden {
    tree: Vec<ScanTreeCase>,
    errors: Vec<ScanErrorCase>,
}

fn assert_scan_node_matches(actual: &ScannedNode, expected: &ScanNodeCase, path: &str) {
    assert_eq!(actual.tag, expected.tag, "{path}: tag mismatch");
    assert_eq!(actual.start, expected.start, "{path}: start mismatch");
    assert_eq!(actual.end, expected.end, "{path}: end mismatch");
    assert_eq!(
        actual.content_start, expected.content_start,
        "{path}: contentStart mismatch"
    );
    assert_eq!(
        actual.content_end, expected.content_end,
        "{path}: contentEnd mismatch"
    );
    assert_eq!(
        actual.self_closing, expected.self_closing,
        "{path}: selfClosing mismatch"
    );
    assert_eq!(
        actual.attributes.len(),
        expected.attributes.len(),
        "{path}: attribute count mismatch"
    );
    for (i, (a, e)) in actual
        .attributes
        .iter()
        .zip(expected.attributes.iter())
        .enumerate()
    {
        assert_eq!(a.name, e.name, "{path}: attribute[{i}].name mismatch");
        assert_eq!(a.value, e.value, "{path}: attribute[{i}].value mismatch");
        assert_eq!(a.start, e.start, "{path}: attribute[{i}].start mismatch");
        assert_eq!(a.end, e.end, "{path}: attribute[{i}].end mismatch");
    }
    assert_eq!(
        actual.children.len(),
        expected.children.len(),
        "{path}: children count mismatch"
    );
    for (i, (a, e)) in actual
        .children
        .iter()
        .zip(expected.children.iter())
        .enumerate()
    {
        assert_scan_node_matches(a, e, &format!("{path}/children[{i}]"));
    }
}

#[test]
fn scan_document_matches_ts_reference_tree_and_error_cases() {
    let raw = fs::read_to_string(golden_path("scan.json"))
        .expect("tests/golden/scan.json must exist — run `node scripts/gen-golden.mjs`");
    let golden: ScanGolden = serde_json::from_str(&raw).expect("golden file must be valid JSON");

    for case in &golden.tree {
        let actual = scan_document(&case.svg).unwrap_or_else(|err| {
            panic!(
                "case {:?}: expected scan_document to succeed, got {:?}",
                case.label,
                err.message()
            )
        });
        assert_eq!(
            actual.len(),
            case.expected.len(),
            "case {:?}: top-level node count mismatch",
            case.label
        );
        for (i, (a, e)) in actual.iter().zip(case.expected.iter()).enumerate() {
            assert_scan_node_matches(a, e, &format!("case {:?} [{}]", case.label, i));
        }
    }

    for case in &golden.errors {
        let err = scan_document(&case.svg).expect_err(&format!(
            "case {:?}: expected scan_document to fail",
            case.label
        ));
        assert_eq!(
            err.message(),
            case.expected_message,
            "case {:?}: error message mismatch",
            case.label
        );
    }
}

// --- bbox.json ----------------------------------------------------------
//
// NOOP-292 (Review round 1, NOOP-283, FAIL item 1): one golden case per
// primitive/element kind plan A9 requires — rect/ellipse/line/path
// (including the elliptical-arc rejection)/group/table/text — each
// compared as its four `format_svg_number` fields, run through the real
// `primitiveBounds`/`elementBounds`/`pathBounds` (`scripts/gen-golden.mjs`'s
// `genBbox`).

#[derive(Deserialize)]
struct FormattedRectCase {
    x: String,
    y: String,
    width: String,
    height: String,
}

#[derive(Deserialize)]
struct BboxPrimitiveCase {
    label: String,
    tag: String,
    attrs: HashMap<String, String>,
    expected: FormattedRectCase,
}

#[derive(Deserialize)]
struct BboxPathOkCase {
    label: String,
    d: String,
    expected: FormattedRectCase,
}

#[derive(Deserialize)]
struct BboxPathArcCase {
    label: String,
    d: String,
    #[serde(rename = "expectedError")]
    expected_error: String,
}

#[derive(Deserialize)]
struct BboxPathCases {
    ok: BboxPathOkCase,
    #[serde(rename = "arcRejected")]
    arc_rejected: BboxPathArcCase,
}

#[derive(Deserialize)]
struct BboxGroupCase {
    label: String,
    expected: FormattedRectCase,
}

#[derive(Deserialize)]
struct BboxTableCase {
    label: String,
    cols: Vec<f64>,
    rows: Vec<f64>,
    expected: FormattedRectCase,
}

#[derive(Deserialize)]
struct BboxTextCase {
    label: String,
    attrs: HashMap<String, String>,
    text: String,
    expected: FormattedRectCase,
}

#[derive(Deserialize)]
struct BboxGolden {
    primitives: Vec<BboxPrimitiveCase>,
    path: BboxPathCases,
    group: BboxGroupCase,
    table: BboxTableCase,
    text: BboxTextCase,
}

fn primitive_from_attrs(tag: &str, attrs: &HashMap<String, String>) -> SlidePrimitive {
    SlidePrimitive {
        tag: tag.to_string(),
        attrs: attrs.iter().map(|(k, v)| (k.clone(), v.clone())).collect(),
        text: String::new(),
        tspan_count: 0,
        runs: Vec::new(),
    }
}

fn bbox_leaf_element(
    id: &str,
    kind: SlideElementKind,
    primitives: Vec<SlidePrimitive>,
) -> SlideElement {
    SlideElement {
        id: id.to_string(),
        name: None,
        media: None,
        kind,
        transform: None,
        matrix: IDENTITY,
        children: Vec::new(),
        primitives,
        text_width: None,
        text_height: None,
        text_align: TextAlign::Left,
        table: None,
    }
}

fn assert_formatted_rect_eq(
    actual: &co_motion::geometry::bbox::FormattedBbox,
    expected: &FormattedRectCase,
    label: &str,
) {
    assert_eq!(actual.x, expected.x, "{label}: x mismatch");
    assert_eq!(actual.y, expected.y, "{label}: y mismatch");
    assert_eq!(actual.width, expected.width, "{label}: width mismatch");
    assert_eq!(actual.height, expected.height, "{label}: height mismatch");
}

#[test]
fn bbox_matches_ts_reference_for_every_primitive_and_element_kind() {
    let raw = fs::read_to_string(golden_path("bbox.json"))
        .expect("tests/golden/bbox.json must exist — run `node scripts/gen-golden.mjs`");
    let golden: BboxGolden = serde_json::from_str(&raw).expect("golden file must be valid JSON");

    for case in &golden.primitives {
        let primitive = primitive_from_attrs(&case.tag, &case.attrs);
        let bbox = primitive_bounds(&primitive, None)
            .unwrap_or_else(|err| panic!("case {:?}: {:?}", case.label, err.message()));
        assert_formatted_rect_eq(&format_bbox(&bbox), &case.expected, &case.label);
    }

    let ok_bbox = path_bounds(&golden.path.ok.d).expect("path-cubic-bezier case must succeed");
    assert_formatted_rect_eq(
        &format_bbox(&ok_bbox),
        &golden.path.ok.expected,
        &golden.path.ok.label,
    );

    let arc_err = path_bounds(&golden.path.arc_rejected.d).expect_err("arc path must be rejected");
    assert_eq!(
        arc_err.message(),
        golden.path.arc_rejected.expected_error,
        "case {:?}: arc rejection message mismatch",
        golden.path.arc_rejected.label
    );

    // group: union of two children's transformed boxes.
    let child_a = bbox_leaf_element(
        "child-a",
        SlideElementKind::Rect,
        vec![primitive_from_attrs(
            "rect",
            &HashMap::from([
                ("x".to_string(), "2".to_string()),
                ("y".to_string(), "3".to_string()),
                ("width".to_string(), "8".to_string()),
                ("height".to_string(), "6".to_string()),
            ]),
        )],
    );
    let child_b = bbox_leaf_element(
        "child-b",
        SlideElementKind::Ellipse,
        vec![primitive_from_attrs(
            "ellipse",
            &HashMap::from([
                ("cx".to_string(), "30".to_string()),
                ("cy".to_string(), "10".to_string()),
                ("rx".to_string(), "4".to_string()),
                ("ry".to_string(), "2".to_string()),
            ]),
        )],
    );
    let mut group = bbox_leaf_element("group-1", SlideElementKind::Group, Vec::new());
    group.children = vec![child_a, child_b];
    let options = ElementBoundsOptions {
        ancestors: &[],
        fonts: None,
    };
    let group_bbox = element_bounds(&group, &options).expect("group bbox must succeed");
    assert_formatted_rect_eq(
        &format_bbox(&group_bbox),
        &golden.group.expected,
        &golden.group.label,
    );

    // table: declared grid extent, not a primitive union.
    let mut table_element = bbox_leaf_element("table-1", SlideElementKind::Table, Vec::new());
    table_element.table = Some(TableGrid {
        cols: golden.table.cols.clone(),
        rows: golden.table.rows.clone(),
    });
    let table_bbox = element_bounds(&table_element, &options).expect("table bbox must succeed");
    assert_formatted_rect_eq(
        &format_bbox(&table_bbox),
        &golden.table.expected,
        &golden.table.label,
    );

    // text: a plain `<text>` (no tspans), measured via the real embedded
    // default font — the same physical .ttf `packages/core/dist`'s
    // `parseFont` read to produce this golden fixture.
    let font = parse_font(DEFAULT_FONT_BYTES).expect("embedded default font must parse");
    let fonts: HashMap<String, Box<dyn FontMetrics>> = HashMap::from([(
        "Noto Sans TC".to_string(),
        Box::new(font) as Box<dyn FontMetrics>,
    )]);
    let text_primitive = SlidePrimitive {
        text: golden.text.text.clone(),
        ..primitive_from_attrs("text", &golden.text.attrs)
    };
    let text_context = TextBoundsContext {
        fonts: &fonts,
        text_width: None,
        text_height: None,
        element_id: "text-1".to_string(),
    };
    let text_bbox =
        primitive_bounds(&text_primitive, Some(&text_context)).expect("text bbox must succeed");
    assert_formatted_rect_eq(
        &format_bbox(&text_bbox),
        &golden.text.expected,
        &golden.text.label,
    );
}

// --- font.json ------------------------------------------------------------
//
// NOOP-292 (Review round 1, NOOP-283, FAIL item 1): `parseFont`'s line
// metrics plus >= 50 `measureTextWidth` golden cases, run against the real
// bundled font (`scripts/gen-golden.mjs`'s `genFont`) — font.rs and
// metrics.rs had no golden coverage at all before this.

#[derive(Deserialize)]
struct FontMetricsCase {
    #[serde(rename = "unitsPerEm")]
    units_per_em: u16,
    ascender: i16,
    descender: i16,
    #[serde(rename = "lineGap")]
    line_gap: i16,
}

#[derive(Deserialize)]
struct MeasureTextWidthCase {
    text: String,
    #[serde(rename = "fontSizePx")]
    font_size_px: f64,
    expected: String,
}

#[derive(Deserialize)]
struct FontGolden {
    metrics: FontMetricsCase,
    #[serde(rename = "measureTextWidth")]
    measure_text_width: Vec<MeasureTextWidthCase>,
}

#[test]
fn font_metrics_and_measure_text_width_match_ts_reference() {
    let raw = fs::read_to_string(golden_path("font.json"))
        .expect("tests/golden/font.json must exist — run `node scripts/gen-golden.mjs`");
    let golden: FontGolden = serde_json::from_str(&raw).expect("golden file must be valid JSON");
    assert!(
        golden.measure_text_width.len() >= 50,
        "plan A9 requires >= 50 measureTextWidth golden cases, found {}",
        golden.measure_text_width.len()
    );

    let font = parse_font(DEFAULT_FONT_BYTES).expect("embedded default font must parse");
    assert_eq!(
        font.units_per_em(),
        golden.metrics.units_per_em,
        "unitsPerEm mismatch"
    );
    assert_eq!(
        font.ascender(),
        golden.metrics.ascender,
        "ascender mismatch"
    );
    assert_eq!(
        font.descender(),
        golden.metrics.descender,
        "descender mismatch"
    );
    assert_eq!(font.line_gap(), golden.metrics.line_gap, "lineGap mismatch");

    let mut failures = Vec::new();
    for case in &golden.measure_text_width {
        let actual = measure_text_width(&font, &case.text, case.font_size_px)
            .unwrap_or_else(|err| panic!("text={:?}: {:?}", case.text, err.message()));
        let formatted = format_svg_number(actual);
        if formatted != case.expected {
            failures.push(format!(
                "text={:?} fontSizePx={} expected={:?} actual={:?}",
                case.text, case.font_size_px, case.expected, formatted
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "measureTextWidth mismatches against TS golden data:\n{}",
        failures.join("\n")
    );
}

// --- text_wrap_extra_cases.json --------------------------------------------
//
// NOOP-292 (Review round 1, NOOP-283, FAIL item 1): the plan's single
// `text_wrap_fixture` (full CLI round trip) doesn't cover CJK-only,
// ASCII-only, an explicit hard break, list-paragraph indents, a single word
// wider than the box, or an empty paragraph. These six run
// `wrapText`/`renderTextBoxContent` directly against the real bundled font
// (`scripts/gen-golden.mjs`'s `genTextWrapExtraCases`).

#[derive(Deserialize)]
struct TextWrapExtraInput {
    text: String,
    width: f64,
    #[serde(rename = "fontSizePx")]
    font_size_px: f64,
    #[serde(default)]
    indents: Option<Vec<f64>>,
}

#[derive(Deserialize)]
struct TextWrapExtraCase {
    label: String,
    input: TextWrapExtraInput,
    #[serde(rename = "expectedInnerMarkup")]
    expected_inner_markup: String,
    #[serde(rename = "expectedTextHeight")]
    expected_text_height: String,
}

#[test]
fn text_wrap_extra_cases_match_ts_reference() {
    let raw = fs::read_to_string(golden_path("text_wrap_extra_cases.json")).expect(
        "tests/golden/text_wrap_extra_cases.json must exist — run `node scripts/gen-golden.mjs`",
    );
    let cases: Vec<TextWrapExtraCase> =
        serde_json::from_str(&raw).expect("golden file must be valid JSON");
    assert!(
        cases.len() >= 6,
        "plan NOOP-292 requires >= 6 supplementary text-wrap golden cases, found {}",
        cases.len()
    );

    let font = parse_font(DEFAULT_FONT_BYTES).expect("embedded default font must parse");
    let mut failures = Vec::new();
    for case in &cases {
        let options = WrapOptions {
            width: case.input.width,
            font: &font,
            font_size_px: case.input.font_size_px,
            align: Align::Left,
            indents: case.input.indents.as_deref(),
        };
        let wrapped = wrap_text(&case.input.text, &options)
            .unwrap_or_else(|err| panic!("case {:?}: {:?}", case.label, err.message()));
        let markup = render_text_box_content(&wrapped.lines, &[]);
        let height = format_svg_number(wrapped.height);
        if markup != case.expected_inner_markup || height != case.expected_text_height {
            failures.push(format!(
                "case={:?}\n  expected_markup={:?}\n  actual_markup={:?}\n  expected_height={:?}\n  actual_height={:?}",
                case.label, case.expected_inner_markup, markup, case.expected_text_height, height
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "text-wrap extra-case mismatches against TS golden data:\n{}",
        failures.join("\n")
    );
}

// ---------------------------------------------------------------------------
// [E4.T4] A2: every repo `project.json` fixture, packed and opened through
// Rust, ends up at `formatVersion` 4, and `pack` -> `open` round-trips the
// resulting content exactly (plan §5 A2). Not a TS-golden comparison — a
// self-contained Rust integration test over the crate's own `container`/
// `workspace::migrate` public API, hence living here (boundary 2) rather
// than in `cli_golden.rs` (a CLI process boundary these functions are
// underneath).
// ---------------------------------------------------------------------------

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("repo root must exist")
}

/// Every directory under `demo/`, `e2e/fixtures/*/`, `fixtures/skills/*/`
/// that has its own `project.json` — 27 as of this ticket (§5 A2's own
/// count, re-derived here rather than hard-coded so a fixture added later
/// is picked up automatically).
fn fixture_directories() -> Vec<PathBuf> {
    let root = repo_root();
    let mut dirs = Vec::new();
    for top in ["demo", "e2e/fixtures", "fixtures/skills"] {
        let top_path = root.join(top);
        if top_path.join("project.json").is_file() {
            dirs.push(top_path.clone());
        }
        let Ok(entries) = fs::read_dir(&top_path) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() && path.join("project.json").is_file() {
                dirs.push(path);
            }
        }
    }
    dirs
}

/// Recursively collects every file under `dir` into a `relative path (POSIX
/// separators) -> bytes` map — the "equivalence" this test and A2 both use:
/// the zip container's own bytes are never compared (compression level is
/// not part of the format), only the fully-unpacked content mapping.
fn collect_tree(dir: &Path) -> BTreeMap<String, Vec<u8>> {
    fn walk(root: &Path, current: &Path, into: &mut BTreeMap<String, Vec<u8>>) {
        for entry in fs::read_dir(current).unwrap().flatten() {
            let path = entry.path();
            if path.is_dir() {
                walk(root, &path, into);
            } else if path.is_file() {
                let relative = path
                    .strip_prefix(root)
                    .unwrap()
                    .to_string_lossy()
                    .replace('\\', "/");
                into.insert(relative, fs::read(&path).unwrap());
            }
        }
    }
    let mut map = BTreeMap::new();
    walk(dir, dir, &mut map);
    map
}

fn temp_dir(label: &str) -> PathBuf {
    let dir = env::temp_dir().join(format!(
        "co-motion-unit-golden-{label}-{}",
        std::process::id()
    ));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).unwrap();
    dir
}

#[test]
fn every_repo_fixture_migrates_to_formatversion_4_and_pack_open_round_trips() {
    let dirs = fixture_directories();
    assert_eq!(
        dirs.len(),
        27,
        "expected exactly 27 project.json fixtures under demo/e2e/fixtures/fixtures/skills, found {}",
        dirs.len()
    );

    let scratch = temp_dir("fixture-roundtrip");
    let mut failures = Vec::new();

    for (i, source_dir) in dirs.iter().enumerate() {
        let first_comot = scratch.join(format!("{i}-first.comot"));
        let first_work = scratch.join(format!("{i}-first-work"));
        if let Err(err) = pack_directory(source_dir, &first_comot) {
            failures.push(format!(
                "{}: pack failed: {}",
                source_dir.display(),
                err.message()
            ));
            continue;
        }
        if let Err(err) = unpack_container(&first_comot, &first_work) {
            failures.push(format!(
                "{}: unpack failed: {}",
                source_dir.display(),
                err.message()
            ));
            continue;
        }
        if let Err(err) = migrate_to_v4(&first_work) {
            failures.push(format!(
                "{}: migrate failed: {}",
                source_dir.display(),
                err.message()
            ));
            continue;
        }

        let project: serde_json::Value = match fs::read_to_string(first_work.join("project.json")) {
            Ok(text) => serde_json::from_str(&text).unwrap(),
            Err(err) => {
                failures.push(format!(
                    "{}: could not read migrated project.json: {err}",
                    source_dir.display()
                ));
                continue;
            }
        };
        if project["formatVersion"] != serde_json::json!(4) {
            failures.push(format!(
                "{}: formatVersion is {:?}, not 4",
                source_dir.display(),
                project["formatVersion"]
            ));
        }
        if !project.get("fonts").is_some_and(|v| v.is_array()) {
            failures.push(format!(
                "{}: fonts key missing or not an array after migration",
                source_dir.display()
            ));
        }
        if project.get("transition").is_some() {
            failures.push(format!(
                "{}: transition key still present after migration",
                source_dir.display()
            ));
        }
        if let Some(templates) = project.get("templates").and_then(|v| v.as_array()) {
            if !templates.iter().all(|t| t.is_object()) {
                failures.push(format!(
                    "{}: templates contains a non-object entry after migration",
                    source_dir.display()
                ));
            }
        }

        // pack -> open round-trip: second pack/unpack of the ALREADY-v4
        // work dir must produce byte-identical content to the first.
        let second_comot = scratch.join(format!("{i}-second.comot"));
        let second_work = scratch.join(format!("{i}-second-work"));
        if let Err(err) = pack_directory(&first_work, &second_comot) {
            failures.push(format!(
                "{}: second pack failed: {}",
                source_dir.display(),
                err.message()
            ));
            continue;
        }
        if let Err(err) = unpack_container(&second_comot, &second_work) {
            failures.push(format!(
                "{}: second unpack failed: {}",
                source_dir.display(),
                err.message()
            ));
            continue;
        }
        // The second unpack is already formatVersion 4 — migrate_to_v4 must
        // be a byte-identical no-op (§4.2's own contract).
        let before_second_migrate = fs::read_to_string(second_work.join("project.json")).unwrap();
        migrate_to_v4(&second_work).unwrap();
        let after_second_migrate = fs::read_to_string(second_work.join("project.json")).unwrap();
        if before_second_migrate != after_second_migrate {
            failures.push(format!(
                "{}: migrate_to_v4 on an already-v4 work dir was not a byte-identical no-op",
                source_dir.display()
            ));
        }

        let first_tree = collect_tree(&first_work);
        let second_tree = collect_tree(&second_work);
        if first_tree != second_tree {
            let only_in_first: Vec<&String> = first_tree
                .keys()
                .filter(|k| !second_tree.contains_key(*k))
                .collect();
            let only_in_second: Vec<&String> = second_tree
                .keys()
                .filter(|k| !first_tree.contains_key(*k))
                .collect();
            failures.push(format!(
                "{}: pack->open round-trip diverged (only_in_first={only_in_first:?}, only_in_second={only_in_second:?})",
                source_dir.display()
            ));
        }
    }

    fs::remove_dir_all(&scratch).ok();
    assert!(
        failures.is_empty(),
        "A2 fixture migration/round-trip failures:\n{}",
        failures.join("\n")
    );
}

/// A synthesized fixture (no repo fixture carries `transition`, per
/// comot-format.md's own note): `transition: "fade"` with two slides, one
/// already carrying `<comot:transition>`. The one without gets
/// `enter="fade" enter-duration="0.4" exit="none" exit-duration="0.5"`; the
/// one that already has one is left byte-for-byte untouched; the
/// `project.json`'s `transition` key disappears either way.
#[test]
fn synthesized_legacy_fade_transition_migrates_only_the_slide_without_one() {
    let work = temp_dir("synthesized-fade");
    fs::create_dir_all(work.join("slides")).unwrap();
    let untouched_slide = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 1280 720\"><metadata><comot:transition xmlns:comot=\"https://co-motion.dev/ns\" enter=\"zoom\" enter-duration=\"1\" exit=\"none\" exit-duration=\"0.5\"/></metadata></svg>\n";
    fs::write(
        work.join("slides/001.svg"),
        "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 1280 720\"></svg>\n",
    )
    .unwrap();
    fs::write(work.join("slides/002.svg"), untouched_slide).unwrap();
    fs::write(
        work.join("project.json"),
        r#"{"formatVersion":2,"name":"Legacy Fade","canvas":{"width":1280,"height":720},"slides":["slides/001.svg","slides/002.svg"],"transition":"fade"}"#,
    )
    .unwrap();

    migrate_to_v4(&work).unwrap();

    let migrated_slide_1 = fs::read_to_string(work.join("slides/001.svg")).unwrap();
    assert!(
        migrated_slide_1
            .contains("enter=\"fade\" enter-duration=\"0.4\" exit=\"none\" exit-duration=\"0.5\"")
    );
    let slide_2_after = fs::read_to_string(work.join("slides/002.svg")).unwrap();
    assert_eq!(
        slide_2_after, untouched_slide,
        "a slide that already had transition metadata must be byte-identical after migration"
    );

    let project: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(work.join("project.json")).unwrap()).unwrap();
    assert_eq!(project["formatVersion"], 4);
    assert!(project.get("transition").is_none());

    fs::remove_dir_all(&work).ok();
}

/// The frozen `project.json` write format (plan §4.2's "凍結格式"):
/// `serde_json`'s 2-space pretty printer, exactly one trailing newline,
/// existing keys keep their original position when their value changes,
/// and a newly-added key (`fonts`) lands at the end.
#[test]
fn migrated_project_json_uses_the_frozen_write_format() {
    let work = temp_dir("frozen-format");
    fs::write(work.join("project.json"), r#"{"formatVersion":1,"name":"X","canvas":{"width":1,"height":1},"slides":[],"mystery":true}"#).unwrap();

    migrate_to_v4(&work).unwrap();

    let text = fs::read_to_string(work.join("project.json")).unwrap();
    assert!(
        text.ends_with("}\n"),
        "must end in exactly one trailing newline"
    );
    assert!(
        !text.ends_with("}\n\n"),
        "must not have a double trailing newline"
    );
    assert!(
        text.contains("{\n  \"formatVersion\": 4,\n  \"name\": \"X\","),
        "must use 2-space indentation with formatVersion in its original first position"
    );
    let keys: Vec<&str> = text
        .lines()
        .filter_map(|line| line.trim_start().split(':').next())
        .filter(|k| k.starts_with('"'))
        .collect();
    assert_eq!(
        keys,
        vec![
            "\"formatVersion\"",
            "\"name\"",
            "\"canvas\"",
            "\"width\"",
            "\"height\"",
            "\"slides\"",
            "\"mystery\"",
            "\"fonts\""
        ]
    );

    fs::remove_dir_all(&work).ok();
}
